Repository onnx/onnx, pull requests merged in 2020-08, with the labels that each got.

#2611 Fixed CumSum axis is not optional and test case errors
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/cumsum.py
  onnx/backend/test/data/node/test_cumsum_1d/model.onnx
  onnx/backend/test/data/node/test_cumsum_1d/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_cumsum_1d_exclusive/model.onnx
  onnx/backend/test/data/node/test_cumsum_1d_exclusive/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_cumsum_1d_reverse/model.onnx
  onnx/backend/test/data/node/test_cumsum_1d_reverse/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_cumsum_1d_reverse_exclusive/model.onnx
  onnx/backend/test/data/node/test_cumsum_1d_reverse_exclusive/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_cumsum_2d_axis_0/model.onnx
  onnx/backend/test/data/node/test_cumsum_2d_axis_0/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_cumsum_2d_axis_1/model.onnx
  onnx/backend/test/data/node/test_cumsum_2d_axis_1/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_cumsum_2d_negative_axis/model.onnx
  onnx/backend/test/data/node/test_cumsum_2d_negative_axis/test_data_set_0/input_1.pb
  onnx/defs/math/defs.cc
Labels: operator

#2948 Doc update for Resize to correct some wrong information
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
Labels: documentation, operator

#2937 Declaration about shape info for graph I/O and node I/O in IR.md
  docs/IR.md
Labels: documentation, ir

#2892 Tag the differentiable variables in RNN operator
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/rnn/defs.cc
Labels: training

#2950 Add nullptr check to type inference mtds to avoid segfaults
  onnx/defs/math/defs.cc
  onnx/defs/math/old.cc
  onnx/defs/sequence/defs.cc
  onnx/defs/tensor/defs.cc
Labels: bug, shape inference

#2964 Remove GraphCall
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/defs/operator_sets_preview.h
  onnx/defs/training/defs.cc
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
Labels: training

#2966 Define differentiable variables for logical operators
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/logical/defs.cc
Labels: training
