Repository onnx/onnx, pull requests merged in 2020-06, with the labels that each got.

#2723 Add tag to define differentiable/non-differrentiable variables
  docs/Changelog-ml.md
  docs/Changelog.md
  docs/Operators-ml.md
  docs/Operators.md
  onnx/cpp2py_export.cc
  onnx/defs/gen_doc.py
  onnx/defs/schema.cc
  onnx/defs/schema.h
  onnx/defs/tensor/defs.cc
  onnx/onnx_cpp2py_export/defs.pyi
Labels: training

#2772 Add support for per-axis scaling for QDQ linear nodes
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/dequantizelinear.py
  onnx/backend/test/case/node/quantizelinear.py
  onnx/backend/test/data/node/test_dequantizelinear_axis/model.onnx
  onnx/backend/test/data/node/test_dequantizelinear_axis/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_dequantizelinear_axis/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_dequantizelinear_axis/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_dequantizelinear_axis/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_quantizelinear_axis/model.onnx
  onnx/backend/test/data/node/test_quantizelinear_axis/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_quantizelinear_axis/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_quantizelinear_axis/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_quantizelinear_axis/test_data_set_0/output_0.pb
  onnx/defs/operator_sets.h
  onnx/defs/quantization/defs.cc
  onnx/defs/quantization/old.cc
Labels: operator

#2589 Clarify the introduction
  docs/IR.md
Labels: documentation
