Repository onnx/onnx, pull requests merged in 2020-07, with the labels that each got.

#2870 Update ort version in CircleCI
  .circleci/build.sh
Labels: build pipelines

#2794 Add document to explain how to define operator's differentiability
  docs/DefineDifferentiability.md
Labels: operator, training

#2896 Differentiability Tags for Tensor Ops
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
Labels: training

#2893 Define differentiability of Pool/Conv Ops
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/nn/defs.cc
Labels: training
