Repository onnx/onnx, pull requests merged in 2021-05, with the labels that each got.

#3480 Fix Linux release CI: Correct manylinux wheel name
  .github/workflows/manylinux/entrypoint.sh
  .github/workflows/manylinux/test_package_i686.sh
  .github/workflows/release_linux_x86_64.yml
Labels: build pipelines

#3465 Fix shape inference for Squeeze without axes
  onnx/defs/tensor/defs.cc
Labels: shape inference

#3470 Add a PR label to manually trigger release CIs
  .github/workflows/release_linux_i686.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
Labels: build pipelines, run release CIs

#3472 Fix misleading global pooling test-case code
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/globalaveragepool.py
  onnx/backend/test/case/node/globalmaxpool.py
Labels: run release CIs

#3407 Adding optional type
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/__init__.py
  onnx/backend/test/case/node/if.py
  onnx/backend/test/case/node/loop.py
  onnx/backend/test/cpp/driver/test_driver.cc
  onnx/backend/test/cpp/driver/test_driver.h
  onnx/backend/test/cpp/driver_test.cc
  onnx/checker.cc
  onnx/checker.h
  onnx/common/ir.h
  onnx/common/ir_pb_converter.cc
  onnx/defs/attr_proto_util.cc
  onnx/defs/optional/defs.cc
  onnx/helper.py
  onnx/mapping.py
  onnx/numpy_helper.py
  onnx/onnx-data.in.proto
  onnx/onnx-data.proto
  onnx/onnx-data.proto3
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
  onnx/test/helper_test.py
  onnx/test/shape_inference_test.py
  tools/protoc-gen-mypy.py
Labels: infrastructure, operator
