Repository onnx/onnx, pull requests merged in 2021-06, with the labels that each got.

#3513 crash fix
  onnx/defs/math/defs.cc
  onnx/defs/math/old.cc
Labels: bug

#3516 Fix Squeeze shape inference
  onnx/defs/tensor/defs.cc
Labels: operator, shape inference

#3527 Fix weekly-CI failure: correct protobuf installation and skip list
  .github/workflows/weekly_mac_ci.yml
  workflow_scripts/config.py
Labels: build pipelines

#3431 Adding Bernoulli operator
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/bernoulli.py
  onnx/backend/test/data/node/test_bernoulli/model.onnx
  onnx/backend/test/data/node/test_bernoulli/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_bernoulli/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_bernoulli_double/model.onnx
  onnx/backend/test/data/node/test_bernoulli_double/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_bernoulli_double/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_bernoulli_double_expanded/model.onnx
  onnx/backend/test/data/node/test_bernoulli_double_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_bernoulli_double_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_bernoulli_expanded/model.onnx
  onnx/backend/test/data/node/test_bernoulli_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_bernoulli_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_bernoulli_seed/model.onnx
  onnx/backend/test/data/node/test_bernoulli_seed/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_bernoulli_seed/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_bernoulli_seed_expanded/model.onnx
  onnx/backend/test/data/node/test_bernoulli_seed_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_bernoulli_seed_expanded/test_data_set_0/output_0.pb
  onnx/defs/generator/defs.cc
  onnx/defs/operator_sets.h
  onnx/test/shape_inference_test.py
Labels: operator

#3508 Optional type documentation
  docs/IR.md
  docs/ONNXTypes.md
  onnx/checker.cc
  onnx/cpp2py_export.cc
  onnx/defs/data_type_utils.cc
  onnx/defs/schema.cc
  onnx/defs/schema.h
  onnx/onnx_cpp2py_export/defs.pyi
Labels: documentation

#3539 Add shape inference function for dynamic quantize linear
  onnx/defs/quantization/defs.cc
  onnx/test/shape_inference_test.py
Labels: operator, shape inference

#3518 Symbolic shape inference support-1: symbol generation
  onnx/defs/shape_inference.h
  onnx/helper.py
  onnx/shape_inference.py
  onnx/shape_inference/implementation.cc
  onnx/shape_inference/implementation.h
  onnx/test/cpp/shape_inference_test.cc
  onnx/test/shape_inference_test.py
  onnx/test/symbolic_shape_test.py
Labels: run release CIs, shape inference
