Repository onnx/onnx, pull requests merged in 2021-08, with the labels that each got.

#3306 Remove usage of numpy aliases for builtins (#3305)
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/model/stringnormalizer.py
  onnx/backend/test/case/node/and.py
  onnx/backend/test/case/node/cast.py
  onnx/backend/test/case/node/compress.py
  onnx/backend/test/case/node/if.py
  onnx/backend/test/case/node/loop.py
  onnx/backend/test/case/node/nonzero.py
  onnx/backend/test/case/node/not.py
  onnx/backend/test/case/node/or.py
  onnx/backend/test/case/node/resize.py
  onnx/backend/test/case/node/stringnormalizer.py
  onnx/backend/test/case/node/where.py
  onnx/backend/test/case/node/xor.py
  onnx/mapping.py
  onnx/numpy_helper.py
  onnx/test/numpy_helper_test.py
Labels: run release CIs

#3657 Batchnorm shape inference
  onnx/defs/nn/defs.cc
  onnx/defs/nn/old.cc
  onnx/test/shape_inference_test.py
Labels: operator, shape inference, run release CIs

#3647 Fix build failure using XCode new build system
  CMakeLists.txt
Labels: run release CIs

#3666 Test source distribution in CI; Add a label for manually trigger testing ONNX Model Zoo CI
  .github/workflows/release_mac.yml
  .github/workflows/weekly_mac_ci.yml
  docs/OnnxReleases.md
Labels: build pipelines

#3687 Fix weekly-CI failure: correct the path for twine upload
  .github/workflows/release_mac.yml
Labels: build pipelines, run release CIs
