Repository onnx/onnx, pull requests merged in 2021-12, with the labels that each got.

#3820 Add compose utils
  docs/PythonAPIOverview.md
  onnx/__init__.py
  onnx/compose.py
  onnx/test/compose_test.py
Labels: infrastructure, enhancement

#3810 Check negative index for attributes of Slice-1
  onnx/defs/tensor/old.cc
Labels: shape inference, run release CIs

#3801 Cleanup type cast related warnings
  onnx/common/tensor.h
  onnx/defs/schema.h
  onnx/onnxifi_dummy.c
  onnx/version_converter/adapters/axes_input_to_attribute.h
  onnx/version_converter/adapters/reshape_5_4.h
  onnx/version_converter/adapters/split_13_12.h
Labels: compiler warning

#3859 Sync build documentation in CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: documentation

#3780 [CI][Doc] Add CI Pipelines doc/node tests verification
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/Windows-CI.yml
  .github/workflows/win_no_exception_ci.yml
  docs/CIPipelines.md
  docs/CONTRIBUTING.md
  docs/OnnxReleases.md
  workflow_scripts/config.py
Labels: documentation, build pipelines
