Repository onnx/onnx, pull requests merged in 2021-04, with the labels that each got.

#3364 Implement NonZero shape inference
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/test/shape_inference_test.py
Labels: operator

#3432 Fix Batchnorm type inference for mean and variance and add a test
  onnx/defs/nn/defs.cc
  onnx/test/shape_inference_test.py
Labels: operator

#3401 Add more automated verification for release packages
  .github/workflows/manylinux/test_package_i686.sh
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  onnx/test/test_with_ort.py
Labels: build pipelines

#3440 [Dup] Update spec for Convtranspose to make it sync
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/convtranspose.py
  onnx/backend/test/data/node/test_convtranspose_autopad_same/model.onnx
  onnx/defs/nn/defs.cc
Labels: documentation, operator

#3398 Make SparseTensor type first class citizen.
  onnx/checker.cc
  onnx/defs/data_type_utils.cc
  onnx/defs/shape_inference.h
  onnx/examples/make_model.ipynb
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
  onnx/shape_inference/implementation.cc
  onnx/shape_inference/implementation.h
  onnx/test/cpp/shape_inference_test.cc
Labels: infrastructure, operator

#3412 Add Additional bfloat16 Support to Pow
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/math/defs.cc
  onnx/defs/math/old.cc
  onnx/defs/operator_sets.h
  onnx/defs/schema.h
Labels: operator
