Repository onnx/onnx, pull requests merged in 2022-09, with the labels that each got.

#4411 Plassen/scatter max
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/scatterelements.py
  onnx/backend/test/case/node/scatternd.py
  onnx/backend/test/data/node/test_scatter_elements_with_axis/model.onnx
  onnx/backend/test/data/node/test_scatter_elements_with_duplicate_indices/model.onnx
  onnx/backend/test/data/node/test_scatter_elements_with_negative_indices/model.onnx
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_max/model.onnx
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_max/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_max/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_max/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_max/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_min/model.onnx
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_min/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_min/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_min/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_scatter_elements_with_reduction_min/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_scatter_elements_without_axis/model.onnx
  onnx/backend/test/data/node/test_scatternd/model.onnx
  onnx/backend/test/data/node/test_scatternd_add/model.onnx
  onnx/backend/test/data/node/test_scatternd_max/model.onnx
  onnx/backend/test/data/node/test_scatternd_max/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_scatternd_max/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_scatternd_max/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_scatternd_max/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_scatternd_min/model.onnx
  onnx/backend/test/data/node/test_scatternd_min/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_scatternd_min/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_scatternd_min/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_scatternd_min/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_scatternd_multiply/model.onnx
  onnx/defs/operator_sets.h
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/version_converter/convert.h
Labels: operator

#4470 Use filesystem to load filename to prevent encoding issues on Windows
  CMakeLists.txt
  README.md
  onnx/checker.cc
  onnx/common/path.cc
  onnx/common/path.h
  onnx/test/cpp/common_path_test.cc
  onnx/test/test_external_data.py
Labels: run release CIs, vulnerability

#4508 [1.12.1] Solve vulnerability issue while loading external tensors
  .github/workflows/release_win.yml
  CMakeLists.txt
  README.md
  onnx/checker.cc
  onnx/common/path.cc
  onnx/common/path.h
  onnx/test/cpp/common_path_test.cc
  onnx/test/shape_inference_test.py
  onnx/test/test_external_data.py
  onnx/utils.py
Labels: run release CIs

#4457 Use find_namespace_packages to get needed subdirectories to silent lots of warnings
  setup.py
Labels: build, build pipelines, run release CIs

#4431 Deprecate ONNXIFI: ONNX Interface for Framework Integration
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  CMakeLists.txt
  cmake/summary.cmake
  cmake/unittest.cmake
  docs/ONNXIFI.md
  onnx/backend/test/cpp/driver/test_driver.cc
  onnx/backend/test/cpp/driver/test_driver.h
  onnx/backend/test/cpp/driver_test.cc
  onnx/backend/test/cpp/gtest_utils.cc
  onnx/backend/test/cpp/gtest_utils.h
  onnx/backend/test/cpp/test_main.cc
  onnx/onnxifi.h
  onnx/onnxifi_dummy.c
  onnx/onnxifi_ext.h
  onnx/onnxifi_loader.c
  onnx/onnxifi_loader.h
  onnx/onnxifi_utils.cc
  onnx/onnxifi_utils.h
  onnx/onnxifi_wrapper.c
  onnx/test/cpp/onnxifi_backend_test.cc
  setup.py
Labels: infrastructure, run release CIs

#4517 avoid modifying node when creating test cases
  onnx/backend/test/case/node/__init__.py
Labels: test

#4524 Use GitHub code scanning before retiring deprecated LGTM.com
  .github/workflows/codeql.yml
Labels: build pipelines

#4531 Add vcpkg instruct step
  README.md
Labels: documentation

#4270 Improve mapping and add more tests for make_tensor
  docs/Operators.md
  docs/PythonAPIOverview.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/__init__.py
  onnx/backend/test/case/node/cast.py
  onnx/backend/test/case/node/castlike.py
  onnx/helper.py
  onnx/mapping.py
  onnx/numpy_helper.py
  onnx/test/helper_test.py
  onnx/test/hub_test.py
  setup.cfg
  setup.py
Labels: test, run release CIs, utility

#4551 Fix several issues regarding recent mapping update
  docs/PythonAPIOverview.md
  onnx/helper.py
  onnx/mapping.py
  onnx/numpy_helper.py
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
  onnx/test/helper_test.py
Labels: test, utility

#4498 Install specified mypy version first in Python Lint CI to make mypy version consistent
  .github/workflows/lint.yaml
Labels: build pipelines
