Repository onnx/onnx, pull requests merged in 2022-06, with the labels that each got.

#4234 Fix mapping TensorProto to NumPy for bfloat16
  onnx/helper.py
  onnx/mapping.py
  onnx/test/helper_test.py
Labels: run release CIs, utility

#4243 to build wheels for the branch
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  onnx/test/cpp/parser_test.cc
Labels: run release CIs

#4228 Fix some typos.
  .github/workflows/manylinux/entrypoint.sh
  docs/Changelog-ml.md
  docs/Changelog.md
  docs/MetadataProps.md
  docs/Operators-ml.md
  docs/Operators.md
  docs/TypeDenotation.md
  onnx/compose.py
  onnx/defs/controlflow/defs.cc
  onnx/defs/controlflow/old.cc
  onnx/defs/nn/defs.cc
  onnx/defs/nn/old.cc
  onnx/defs/schema.h
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/defs/traditionalml/defs.cc
  onnx/defs/traditionalml/old.cc
  onnx/test/helper_test.py
  onnx/version_converter/adapters/scan_9_8.h
Labels: documentation

#4224 Make domain check in shape inference consider "ai.onnx" as ""
  onnx/shape_inference/implementation.cc
Labels: shape inference, run release CIs

#4256 Fix: Window functions generate incorrect shape for with symmetric attribute
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/stft.py
  onnx/backend/test/data/node/test_blackmanwindow_expanded/model.onnx
  onnx/backend/test/data/node/test_blackmanwindow_symmetric_expanded/model.onnx
  onnx/backend/test/data/node/test_hammingwindow_expanded/model.onnx
  onnx/backend/test/data/node/test_hammingwindow_symmetric_expanded/model.onnx
  onnx/backend/test/data/node/test_hannwindow_expanded/model.onnx
  onnx/backend/test/data/node/test_hannwindow_symmetric_expanded/model.onnx
  onnx/backend/test/data/node/test_stft/test_data_set_0/output_0.pb
  onnx/defs/math/defs.cc
  onnx/test/shape_inference_test.py
Labels: run release CIs

#4268 Fix sub-graph generation for LN
  onnx/backend/test/data/node/test_layer_normalization_2d_axis0_expanded/model.onnx
  onnx/backend/test/data/node/test_layer_normalization_3d_axis0_epsilon_expanded/model.onnx
  onnx/backend/test/data/node/test_layer_normalization_4d_axis0_expanded/model.onnx
  onnx/defs/nn/defs.cc
Labels: run release CIs

#4235 Update ir.h to support initializer better
  onnx/common/ir.h
  onnx/common/ir_pb_converter.cc
Labels: ir, infrastructure, run release CIs

#4277 Remove reference to numpy.typing
  onnx/numpy_helper.py
Labels: run release CIs

#4279 Verify minimum supported numpy in Windows Release CI
  .github/workflows/release_win.yml
  docs/CIPipelines.md
Labels: build pipelines, run release CIs

#4259 Update README with build modifications
  README.md
Labels: build, documentation

#4282 Fix crash: only traverse graph to add symbols if symbol table presents
  onnx/shape_inference/implementation.cc
Labels: shape inference, run release CIs

#4283 Revert #3979: Checker should validate the node's inputs/outputs have names when Variadic
  onnx/defs/schema.cc
  onnx/test/checker_test.py
Labels: onnx checker, run release CIs

#4246 Print utility extension
  onnx/cpp2py_export.cc
  onnx/defs/parser.cc
  onnx/defs/parser.h
  onnx/defs/printer.cc
  onnx/defs/printer.h
  onnx/onnx_cpp2py_export/parser.pyi
  onnx/onnx_cpp2py_export/printer.pyi
  onnx/parser.py
  onnx/printer.py
  onnx/test/cpp/parser_test.cc
  onnx/test/parser_test.py
  onnx/test/printer_test.py
Labels: utility

#3317 Fix concurrent remove of .proto3.* files during build
  onnx/gen_proto.py
Labels: build, run release CIs

#4296 Create inline lints with github actions
  .github/workflows/lint.yaml
  setup.cfg
  tools/style.sh
Labels: build pipelines
