Repository onnx/onnx, pull requests merged in 2022-03, with the labels that each got.

#3979 Checker should validate the node's inputs/outputs have names when its formal parameter is Variadic
  onnx/defs/schema.cc
  onnx/test/checker_test.py
Labels: onnx checker

#4044 Change the wrong words of second layer `input`
  docs/PythonAPIOverview.md
Labels: documentation

#4059 Loose NumPy requirement to grant more flexibility
  requirements.txt
Labels: build, run release CIs

#3734 Enable Python 3.10 support/add Python 3.10 in release CIs
  .github/workflows/manylinux/entrypoint.sh
  .github/workflows/manylinux/test_package_i686.sh
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_i686.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  .github/workflows/weekly_mac_ci.yml
  .github/workflows/win_no_exception_ci.yml
Labels: build pipelines, run release CIs

#3789 Add shape inference for Expand using symbolic shape input
  onnx/defs/math/defs.cc
  onnx/defs/shape_inference.cc
  onnx/defs/shape_inference.h
  onnx/test/shape_inference_test.py
Labels: shape inference, partial data propagation

#4075 Add config for Stale Bot
  .github/stale.yml
Labels: enhancement

#3908 Clearer description of Slice
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
Labels: spec clarification

#4096 Clarify that op_type is case sensitive
  docs/IR.md
Labels: documentation, spec clarification

#4079 Fix crash: Skip unused value_info for version_converter
  onnx/common/ir_pb_converter.cc
Labels: version converter, run release CIs

#4069 Refactor shape inference
  onnx/shape_inference/implementation.cc
Labels: run release CIs
