Repository onnx/onnx, pull requests merged in 2022-04, with the labels that each got.

#4112 Fix Python 3.10 CI failure: Remove unused LooseVersion
  onnx/examples/np_array_tensorproto.ipynb
Labels: build pipelines, run release CIs

#4108 Fix broken links: slack and code owner
  CODEOWNERS
  README.md
Labels: documentation

#4077 setup.py: Fix author email and make string quoting consistent
  setup.py
Labels: build

#4123 Check whether input type is missing for function shape inference
  onnx/shape_inference/implementation.cc
Labels: shape inference

#4118 Fix a bug in _get_initializer_tensors()
  onnx/external_data_helper.py
Labels: utility

#4125 Fix a minor typo in operator Gather documentation
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
Labels: documentation

#3667 CMakeLists: Do not write generated files to the source dir
  CMakeLists.txt
Labels: build, run release CIs

#4107 Fix broken status badge in Readme.md
  README.md
Labels: documentation

#4137 Add instruction for bumping opset version after ONNX release
  docs/OnnxReleases.md
Labels: documentation

#4127 Shape inference refactoring part 2
  onnx/shape_inference/implementation.cc
Labels: shape inference, run release CIs

#4157 typo: Update CIPipelines.md
  docs/CIPipelines.md
Labels: documentation

#4163 Update shape inference documentation
  docs/ShapeInference.md
Labels: documentation

#4140 Fix bug of resizeShapeInference for Resize13
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/defs/tensor/utils.cc
  onnx/defs/tensor/utils.h
Labels: shape inference
