Repository onnx/onnx, pull requests merged in 2022-08, with the labels that each got.

#4395 use CMAKE_INSTALL_LIBDIR to avoid hardcoded path
  CMakeLists.txt
  README.md
Labels: build, run release CIs

#4401 add docs for cpp tests requiring built libraries
  docs/CONTRIBUTING.md
Labels: documentation

#4379 Upgrade to macos-11 due to macos-10.15 deprecation
  .github/workflows/release_mac.yml
  docs/CIPipelines.md
Labels: build pipelines, run release CIs

#4332 Add new Lint Python CI in the CI document
  docs/CIPipelines.md
  docs/CONTRIBUTING.md
Labels: documentation, build pipelines

#4377 Use fully qualified pathname when loading DLL to prevent security vulnerability
  onnx/onnxifi_loader.c
Labels: vulnerability

#4386 Make C++ and Python check_model consistent
  onnx/checker.cc
  onnx/checker.h
  onnx/checker.py
  onnx/cpp2py_export.cc
  onnx/onnx_cpp2py_export/checker.pyi
Labels: onnx checker

#4351 Specify pairwise conversion behavior for the Cast op
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
Labels: operator

#4388 Allow for both scales and sizes to be provided when one of them is an empty constant
  onnx/defs/tensor/utils.cc
  onnx/test/shape_inference_test.py
Labels: shape inference

#4400 Do not allow to read tensor's external_data outside the model directory
  onnx/checker.cc
  onnx/common/path.cc
  onnx/common/path.h
  onnx/test/cpp/common_path_test.cc
  onnx/test/test_external_data.py
Labels: run release CIs, utility, vulnerability

#4428 [ci] Install ONNX before linting
  .github/workflows/lint.yaml
Labels: build pipelines

#4413 Add an assert to make sure the quantity is reasonable for vsnprintf
  onnx/common/assertions.cc
Labels: run release CIs, vulnerability

#4429 Forbid possible ir_version=0 in IR
  onnx/common/ir_pb_converter.cc
Labels: ir

#4412 Add py.typed to let mypy get stub for type information
  onnx/py.typed
  setup.py
Labels: build, run release CIs

#4437 Remove redundant 'static_cast' in ir_pb_converter.cc
  onnx/common/ir_pb_converter.cc
Labels: ir

#4440 Fix Windows Release Python 3.10 CI failure when building NumPy from source
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  .github/workflows/weekly_mac_ci.yml
  .github/workflows/win_no_exception_ci.yml
Labels: build pipelines, run release CIs

#4441 Update issues template and ONNX Hub doc
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/operator.md
  .github/ISSUE_TEMPLATE/question.md
  docs/Hub.md
Labels: documentation

#4421 to extend OptionalHasElement and OptionalGetElement to accept tensor and sequence types
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/optionalgetelement.py
  onnx/backend/test/case/node/optionalhaselement.py
  onnx/backend/test/data/node/test_optional_get_element/model.onnx
  onnx/backend/test/data/node/test_optional_get_element_optional_sequence/model.onnx
  onnx/backend/test/data/node/test_optional_get_element_optional_sequence/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_optional_get_element_optional_sequence/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_get_element_optional_tensor/model.onnx
  onnx/backend/test/data/node/test_optional_get_element_optional_tensor/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_optional_get_element_optional_tensor/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_get_element_sequence/model.onnx
  onnx/backend/test/data/node/test_optional_get_element_sequence/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_optional_get_element_tensor/model.onnx
  onnx/backend/test/data/node/test_optional_get_element_tensor/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_optional_get_element_tensor/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_has_element/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_empty/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_name_optional_input/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_name_optional_input/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_name_tensor_input/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_name_tensor_input/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_optional_input/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_optional_input/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_tensor_input/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_empty_no_input_tensor_input/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_has_element_empty_optional_input/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_empty_optional_input/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_optional_has_element_empty_optional_input/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_has_element_optional_input/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_optional_input/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_optional_has_element_optional_input/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_optional_has_element_tensor_input/model.onnx
  onnx/backend/test/data/node/test_optional_has_element_tensor_input/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_optional_has_element_tensor_input/test_data_set_0/output_0.pb
  onnx/defs/operator_sets.h
  onnx/defs/optional/defs.cc
  onnx/defs/optional/old.cc
  onnx/version_converter/convert.h
Labels: operator

#4455 Remove sentences about deprecated onnx-docker in docs
  README.md
  community/readme.md
  community/sigs.md
Labels: documentation

#4456 Make check_model with full_check always not modify the model in place
  onnx/checker.cc
  onnx/checker.h
  onnx/shape_inference/implementation.cc
Labels: onnx checker

#4471 Upgrade macOS in azp due to upcoming deprecation
  .azure-pipelines/MacOS-CI.yml
  .github/workflows/release_mac.yml
Labels: build pipelines, run release CIs

#4473 Make ONNX installable even with spaces in path
  CMakeLists.txt
  tools/protoc-gen-mypy.bat
  tools/protoc-gen-mypy.sh.in
Labels: build, run release CIs
