Repository onnx/onnx, pull requests merged in 2023-03, with the labels that each got.

#4953 Remove 3 unnecessary onnx files for backend tests
  onnx/backend/test/data/light/light_densetnet121.onnx
  onnx/backend/test/data/light/light_resnet.onnx
  onnx/backend/test/data/light/light_squeeze.onnx
Labels: test

#4954 Make LRN reference implementation 50x faster
  onnx/reference/ops/op_lrn.py
  onnx/test/reference_evaluator_test.py
Labels: reference implementation

#4955 Fix Windows x86 pipeline failure: handle NumPy behavior in reference
  onnx/reference/ops/op_non_zero.py
  onnx/test/test_backend_reference.py
Labels: run release CIs, reference implementation

#4948 Add run release CIs to cover more pipelines for testing in dependabot
  .github/dependabot.yml
Labels: build pipelines

#4950 Apply ORT 1.14.1 to resolve compatibility issue on Mac
  .github/workflows/release_mac.yml
Labels: build pipelines, run release CIs

#4965 Update function default-attribute documentation
  docs/IR.md
Labels: documentation

#4963 Clarify reduction op inputs can be rank-0 tensors (scalars)
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/reduction/utils.cc
Labels: operator

#4970 Update documentation of optional arguments
  docs/IR.md
Labels: documentation

#4978 Add comments to pyproject.toml to explain how to configure linters
  .lintrunner.toml
  pyproject.toml
Labels: code style

#4969 Fix web content CI: freeze ir_version as a relesed one
  docs/docsgen/source/intro/python.rst
Labels: website content

#4882 Add one backend test for ArrayFeatureExtractor
  docs/Operators-ml.md
  docs/TestCoverage-ml.md
  docs/docsgen/source/expect_onnxruntime.rst
  onnx/backend/test/case/node/__init__.py
  onnx/backend/test/case/node/ai_onnx_ml/array_feature_extractor.py
  onnx/backend/test/data/node/test_ai_onnx_ml_array_feature_extractor/model.onnx
  onnx/backend/test/data/node/test_ai_onnx_ml_array_feature_extractor/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_ai_onnx_ml_array_feature_extractor/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_ai_onnx_ml_array_feature_extractor/test_data_set_0/output_0.pb
  onnx/backend/test/report/coverage.py
  onnx/cpp2py_export.cc
Labels: spec clarification

#5013 Use word "governance" in the readme file
  README.md
Labels: documentation

#4966 Add ONNX Runtime tests in CI pipelines with installed ONNX Runtime
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  onnx/test/reference_evaluator_backend_test.py
  onnx/test/reference_evaluator_ml_test.py
  onnx/test/reference_evaluator_test.py
  onnx/test/test_with_ort.py
Labels: test, build pipelines, run release CIs

#4974 Convert softmax op without knowing the shape
  onnx/test/version_converter_test.py
  onnx/version_converter/adapters/softmax_12_13.h
Labels: version converter

#4980 Fix UnionTypeInfo bug
  onnx/defs/shape_inference.cc
  onnx/test/shape_inference_test.py
Labels: shape inference

#5030 Enable version_conversion for 12 to 13 with ONNX Model Zoo models
  workflow_scripts/config.py
Labels: test

#4783 add DeformConv-19
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/deformconv.py
  onnx/backend/test/data/node/test_acos/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_acosh/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_asin/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_asinh/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_atan/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_atanh/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_basic_deform_conv_with_padding/model.onnx
  onnx/backend/test/data/node/test_basic_deform_conv_with_padding/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_basic_deform_conv_with_padding/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_basic_deform_conv_with_padding/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_basic_deform_conv_with_padding/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_basic_deform_conv_without_padding/model.onnx
  onnx/backend/test/data/node/test_basic_deform_conv_without_padding/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_basic_deform_conv_without_padding/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_basic_deform_conv_without_padding/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_basic_deform_conv_without_padding/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_cosh/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_cosh_example/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_deform_conv_with_mask_bias/model.onnx
  onnx/backend/test/data/node/test_deform_conv_with_mask_bias/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_deform_conv_with_mask_bias/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_deform_conv_with_mask_bias/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_deform_conv_with_mask_bias/test_data_set_0/input_3.pb
  onnx/backend/test/data/node/test_deform_conv_with_mask_bias/test_data_set_0/input_4.pb
  onnx/backend/test/data/node/test_deform_conv_with_mask_bias/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_deform_conv_with_multiple_offset_groups/model.onnx
  onnx/backend/test/data/node/test_deform_conv_with_multiple_offset_groups/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_deform_conv_with_multiple_offset_groups/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_deform_conv_with_multiple_offset_groups/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_deform_conv_with_multiple_offset_groups/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_lrn_default/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_mish/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_mish_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_mvn/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_mvn_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_mvn_expanded_ver18/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_pow/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_do_not_keepdims_example/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_do_not_keepdims_example_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_do_not_keepdims_random/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_do_not_keepdims_random_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_keepdims_example/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_keepdims_example_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_keepdims_random/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_keepdims_random_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_negative_axes_keepdims_example/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_negative_axes_keepdims_example_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_negative_axes_keepdims_random/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_reduce_log_sum_exp_negative_axes_keepdims_random_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_sinh/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_tan/test_data_set_0/output_0.pb
  onnx/defs/nn/defs.cc
  onnx/defs/operator_sets.h
  onnx/reference/ops/_op_list.py
  onnx/reference/ops/op_deform_conv.py
  onnx/test/automatic_upgrade_test.py
Labels: operator

#5039 Build rel-1.13.1 with Protobuf v21 as a onnx branch for PyTorch
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  .azure-pipelines/Windows-CI.yml
  onnx/examples/Protobufs.ipynb
  onnx/examples/check_model.ipynb
  onnx/examples/load_model.ipynb
  onnx/examples/make_model.ipynb
  requirements-release.txt
  requirements.txt
  setup.py
  workflow_scripts/protobuf/build_protobuf_unix.sh
  workflow_scripts/protobuf/build_protobuf_win.ps1
Labels: run release CIs

#5038 fix numpy type in DeformConv python implementation
  onnx/reference/ops/op_deform_conv.py
Labels: run release CIs

#5007 Fix support for negative axes in Pad and CenterCropPad
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/center_crop_pad.py
  onnx/backend/test/case/node/pad.py
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc/model.onnx
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc_expanded/model.onnx
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc_expanded/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_center_crop_pad_crop_negative_axes_hwc_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_constant_pad_negative_axes/model.onnx
  onnx/backend/test/data/node/test_constant_pad_negative_axes/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_constant_pad_negative_axes/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_constant_pad_negative_axes/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_constant_pad_negative_axes/test_data_set_0/input_3.pb
  onnx/backend/test/data/node/test_constant_pad_negative_axes/test_data_set_0/output_0.pb
  onnx/defs/shape_inference.h
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/utils.cc
  onnx/reference/ops/op_center_crop_pad.py
  onnx/reference/ops/op_pad.py
Labels: operator, shape inference

#5044 Enable modern numpy checks
  pyproject.toml
Labels: code style

#5059 Fix typo in Converting Version of an ONNX Model
  docs/PythonAPIOverview.md
Labels: documentation

#5040 Clarify documentation for ReferenceEvaluator, fix type issue in Deform implementation
  onnx/reference/reference_evaluator.py
Labels: documentation

#5062 Switch from the current diff2html-ui.min.js to diff2html-ui-slim.min.js
  docs/docsgen/source/_static/diff2html-ui-slim.min.js
  docs/docsgen/source/_static/diff2html-ui.min.js
  docs/docsgen/source/onnx_sphinx.py
Labels: website content

#5073 Also use `has_context_dependent_function` in sphinx document
  docs/docsgen/source/onnx_sphinx.py
Labels: website content
