Repository onnx/onnx, pull requests merged in 2023-12, with the labels that each got.

#5777 Include pyi files in build
  CMakeLists.txt
  pyproject.toml
  setup.py
  tools/protoc-gen-mypy.py
Labels: build, build pipelines, run release CIs

#5813 Removed unused string_view include
  onnx/defs/parser.cc
Labels: better engineering

#5814 Clean up backend tests for ONNX Runtime
  .azure-pipelines/MacOS-CI.yml
  onnx/test/test_backend_onnxruntime.py
  pyproject.toml
Labels: better engineering

#5820 Use mac-release 10.15
  .github/workflows/release_mac.yml
  onnx/test/test_backend_reference.py
Labels: run release CIs
