Repository onnx/onnx, pull requests merged in 2023-07, with the labels that each got.

#5381 Generate both onnx and onnx-ml operator docs when ONNX_ML=1
  .github/workflows/lint.yml
  docs/CONTRIBUTING.md
  onnx/defs/gen_doc.py
  tools/update_doc.bat
  tools/update_doc.sh
Labels: utility

#5340 Only update Protobuf and NumPy manually for compatibility/set dependabot limit
  .github/dependabot.yml
  requirements.txt
Labels: build pipelines, dependencies

#5398 Dummy dco workflow to enable merge queue
  .github/workflows/dco_merge_group.yml
Labels: build pipelines

#4890 Enable merge queue in pipelines: GitHub Action, AzurePipelines
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  .azure-pipelines/Windows-CI.yml
  .github/workflows/dco_merge_group.yml
  .github/workflows/lint.yml
Labels: build pipelines

#5375 Fix reference implementation for operator CastLike and bfloat16
  onnx/reference/ops/op_cast_like.py
  onnx/reference/ops/op_constant_of_shape.py
  onnx/test/reference_evaluator_test.py
Labels: reference implementation

#5400 [Spec] output_shape for ConvTranspose should not have batch and channels
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/nn/defs.cc
Labels: documentation, spec clarification

#5402 Update Operators.md
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/math/defs.cc
  onnx/defs/math/old.cc
Labels: operator

#5277 Implement GELU as function op
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/gelu.py
  onnx/backend/test/data/node/test_gelu_default_1/model.onnx
  onnx/backend/test/data/node/test_gelu_default_1/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_default_1/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_gelu_default_1_expanded/model.onnx
  onnx/backend/test/data/node/test_gelu_default_1_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_default_1_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_gelu_default_2/model.onnx
  onnx/backend/test/data/node/test_gelu_default_2/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_default_2/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_gelu_default_2_expanded/model.onnx
  onnx/backend/test/data/node/test_gelu_default_2_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_default_2_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_1/model.onnx
  onnx/backend/test/data/node/test_gelu_tanh_1/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_1/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_1_expanded/model.onnx
  onnx/backend/test/data/node/test_gelu_tanh_1_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_1_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_2/model.onnx
  onnx/backend/test/data/node/test_gelu_tanh_2/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_2/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_2_expanded/model.onnx
  onnx/backend/test/data/node/test_gelu_tanh_2_expanded/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_gelu_tanh_2_expanded/test_data_set_0/output_0.pb
  onnx/defs/math/defs.cc
  onnx/defs/operator_sets.h
  onnx/test/automatic_upgrade_test.py
  onnx/test/test_backend_onnxruntime.py
Labels: operator

#5350 StringConcat Operator
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/string_concat.py
  onnx/backend/test/data/node/test_string_concat/model.onnx
  onnx/backend/test/data/node/test_string_concat/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_string_concat/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_string_concat/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_string_concat_broadcasting/model.onnx
  onnx/backend/test/data/node/test_string_concat_broadcasting/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_string_concat_broadcasting/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_string_concat_broadcasting/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_string_concat_empty_string/model.onnx
  onnx/backend/test/data/node/test_string_concat_empty_string/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_string_concat_empty_string/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_string_concat_empty_string/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_string_concat_utf8/model.onnx
  onnx/backend/test/data/node/test_string_concat_utf8/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_string_concat_utf8/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_string_concat_utf8/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_string_concat_zero_dimensional/model.onnx
  onnx/backend/test/data/node/test_string_concat_zero_dimensional/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_string_concat_zero_dimensional/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_string_concat_zero_dimensional/test_data_set_0/output_0.pb
  onnx/defs/nn/defs.cc
  onnx/defs/operator_sets.h
  onnx/defs/text/defs.cc
  onnx/reference/ops/_op_list.py
  onnx/reference/ops/op_string_concat.py
  onnx/reference/reference_evaluator.py
  onnx/test/automatic_upgrade_test.py
  onnx/test/reference_evaluator_test.py
  onnx/test/shape_inference_test.py
  onnx/test/test_backend_onnxruntime.py
Labels: operator

#5422 add community day2023 confluence page link
  README.md
Labels: documentation

#5431 Solve merge queue timeout issue: accelerate windows CI
  .azure-pipelines/Windows-CI.yml
  .github/workflows/codeql.yml
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  .github/workflows/weekly_mac_ci.yml
  .github/workflows/win_no_exception_ci.yml
Labels: build pipelines, run release CIs

#5396 Introduce optional cpplint in CI
  .github/workflows/lint.yml
Labels: code style

#5432 Reduce the burden to run Azure Pipelines and make Windows CI run faster
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  .azure-pipelines/Windows-CI.yml
  .github/workflows/pages.yml
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
Labels: build pipelines

#5395 Bump ruff to v0.0.277 and fix new errors
  onnx/backend/test/case/base.py
  onnx/reference/op_run.py
  onnx/reference/ops/op_non_max_suppression.py
  onnx/reference/reference_evaluator.py
  onnx/test/shape_inference_test.py
  onnx/test/test_backend_onnxruntime.py
  requirements-lintrunner.txt
  setup.py
Labels: code style

#5370 Delete stl_backports.h
  onnx/common/stl_backports.h
  onnx/defs/schema.cc
  onnx/version_converter/BaseConverter.h
  onnx/version_converter/convert.h
Labels: run release CIs

#5435 [Doc] Update README.md regarding Protobuf update and fix typo in Slice-13 spec
  README.md
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
Labels: operator, build, documentation

#5437 Update OnnxReleases.md
  docs/OnnxReleases.md
Labels: documentation
