Repository onnx/onnx, pull requests merged in 2023-08, with the labels that each got.

#5456 Fix rounding issue in conversion to e4m3fn
  onnx/helper.py
  onnx/test/numpy_helper_test.py
  onnx/test/reference_evaluator_test.py
Labels: utility

#5450 Add auto update doc pipeline to help developers update docs
  .github/workflows/auto_update_doc.yml
  .github/workflows/release_linux_x86_64.yml
Labels: documentation, build pipelines

#5401 Add RegexFullMatch operator
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  .azure-pipelines/Windows-CI.yml
  .github/workflows/release_win.yml
  README.md
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/regex_full_match.py
  onnx/backend/test/data/node/test_regex_full_match_basic/model.onnx
  onnx/backend/test/data/node/test_regex_full_match_basic/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_regex_full_match_basic/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_regex_full_match_email_domain/model.onnx
  onnx/backend/test/data/node/test_regex_full_match_email_domain/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_regex_full_match_email_domain/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_regex_full_match_empty/model.onnx
  onnx/backend/test/data/node/test_regex_full_match_empty/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_regex_full_match_empty/test_data_set_0/output_0.pb
  onnx/defs/operator_sets.h
  onnx/defs/text/defs.cc
  onnx/reference/ops/_op_list.py
  onnx/reference/ops/op_regex_full_match.py
  onnx/test/automatic_upgrade_test.py
  onnx/test/reference_evaluator_backend_test.py
  onnx/test/reference_evaluator_test.py
  onnx/test/shape_inference_test.py
  onnx/test/test_backend_onnxruntime.py
  onnx/test/test_backend_reference.py
  requirements-dev.txt
  requirements-reference.txt
  requirements-release.txt
  setup.py
Labels: operator, run release CIs

#5479 Fix missing requirements-reference.txt for installing from source distribution
  MANIFEST.in
  setup.py
Labels: build, build pipelines, run release CIs

#4937 Added Windows ARM64 build support for ONNX
  setup.py
Labels: build, run release CIs

#5486 Always upload SARIF in PR
  .github/workflows/lint.yml
Labels: build pipelines

#5294 Add ImageDecoder operator
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/image_decoder.py
  onnx/backend/test/data/node/test_image_decoder_decode_bmp_rgb/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_bmp_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_bmp_rgb/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg2k_rgb/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg2k_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg2k_rgb/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_bgr/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_bgr/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_bgr/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_grayscale/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_grayscale/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_grayscale/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_rgb/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg_rgb/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_png_rgb/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_png_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_png_rgb/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_pnm_rgb/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_pnm_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_pnm_rgb/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_tiff_rgb/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_tiff_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_tiff_rgb/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_webp_rgb/model.onnx
  onnx/backend/test/data/node/test_image_decoder_decode_webp_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_webp_rgb/test_data_set_0/output_0.pb
  onnx/defs/image/defs.cc
  onnx/defs/operator_sets.h
  onnx/reference/ops/_op_list.py
  onnx/reference/ops/op_image_decoder.py
  onnx/test/automatic_upgrade_test.py
  onnx/test/test_backend_onnxruntime.py
  requirements-dev.txt
  requirements-reference.txt
Labels: operator

#5495 fix build for web assembly
  onnx/checker.cc
Labels: build, run release CIs

#5496 [1.14.1] Cherry pick: fix build for web assembly (#5495)
  VERSION_NUMBER
  onnx/checker.cc
Labels: onnx checker

#5492 Lazy import cv2 only when running reference for ImageDecoder op
  onnx/reference/ops/op_image_decoder.py
  requirements-release.txt
Labels: run release CIs, dependencies, reference implementation

#5434 Add github action to check urls are valid
  .github/workflows/check_urls.yml
  docs/proposals/NLPinONNXproposal.md
  onnx/defs/shape_inference.h
  onnx/reference/ops/aionnxml/op_svm_classifier.py
  onnx/reference/ops/op_qlinear_conv.py
  onnx/reference/reference_evaluator.py
Labels: build pipelines

#5494 Rename source/target to inferred/declared
  onnx/defs/shape_inference.cc
  onnx/defs/shape_inference.h
Labels: shape inference

#5475 Fix Slice shape inference in the case of dynamic inputs
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/test/shape_inference_test.py
Labels: shape inference

#5488 Propagate strict_mode in infer_shape call to subgraphs
  onnx/backend/test/runner/__init__.py
  onnx/cpp2py_export.cc
  onnx/shape_inference/implementation.cc
  onnx/shape_inference/implementation.h
  onnx/test/cpp/shape_inference_test.cc
  onnx/test/inference_function_test.py
  onnx/test/parser_test.py
  onnx/test/test_backend_test.py
Labels: shape inference

#5517 Show human-readable attribute type names in `helper.make_attribute` exception
  onnx/helper.py
  onnx/test/helper_test.py
Labels: utility

#5521 Add double support to tensor attribute LabelEncoder
  docs/Changelog-ml.md
  docs/Operators-ml.md
  onnx/defs/traditionalml/defs.cc
Labels: operator, schema

#5524 Create the onnxtxt serialization format
  onnx/serialization.py
  onnx/test/basic_test.py
Labels: utility

#5531 Specify the build-system in pyproject.toml
  pyproject.toml
Labels: build

#5534 Revert "Specify the build-system in pyproject.toml"
  pyproject.toml
Labels: build, build pipelines

#5536 Specify the build-system in pyproject.toml - second attempt
  .github/workflows/release_mac.yml
  docs/OnnxReleases.md
  pyproject.toml
Labels: build, run release CIs

#5549 Do not raise an exception in printable_graph when shape is not specified
  onnx/helper.py
  onnx/test/helper_test.py
Labels: utility

#5546 Handle initializers in printer
  docs/Syntax.md
  onnx/defs/printer.cc
Labels: documentation, onnx parser

#5540 Squash typos in */defs.cc
  docs/Changelog-ml.md
  docs/Changelog.md
  docs/Operators-ml.md
  docs/Operators.md
  onnx/defs/math/defs.cc
  onnx/defs/math/old.cc
  onnx/defs/nn/defs.cc
  onnx/defs/nn/old.cc
  onnx/defs/quantization/defs.cc
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/defs/traditionalml/defs.cc
  onnx/defs/traditionalml/old.cc
Labels: operator, auto update doc

#5551 After ONNX 1.14.1 release: update main branch and OnnxReleases.md
  docs/OnnxReleases.md
  docs/Versioning.md
  onnx/common/version.h
  onnx/helper.py
Labels: documentation

#5553 Add missing parameter provider when calling InferenceSession for a unit test
  onnx/test/test_backend_onnxruntime.py
  onnx/test/test_with_ort.py
Labels: test, reference implementation

#5556 Minor bug fix in merge graphs.
  onnx/compose.py
Labels: utility
