Repository onnx/onnx, pull requests merged in 2023-04, with the labels that each got.

#5066 Parsing NodeProto and handling optional inputs of functions
  onnx/cpp2py_export.cc
  onnx/defs/parser.cc
  onnx/defs/parser.h
  onnx/defs/printer.cc
  onnx/helper.py
  onnx/onnx_cpp2py_export/parser.pyi
  onnx/parser.py
  onnx/shape_inference/implementation.cc
  onnx/test/cpp/parser_test.cc
  onnx/test/parser_test.py
Labels: onnx parser

#5083 Update Explanation how to handle DCO in a simpler way., Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#5008 Fix reference implementation for Pad and Reduce ops
  onnx/reference/ops/op_pad.py
  onnx/reference/ops/op_reduce_l1.py
  onnx/reference/ops/op_reduce_l2.py
  onnx/reference/ops/op_reduce_max.py
  onnx/reference/ops/op_reduce_mean.py
  onnx/reference/ops/op_reduce_min.py
  onnx/reference/ops/op_reduce_prod.py
  onnx/reference/ops/op_reduce_sum.py
  onnx/reference/ops/op_reduce_sum_square.py
  onnx/test/reference_evaluator_test.py
Labels: reference implementation

#4960 Add expected outputs for light models to make the backend test faster
  .reuse/dep5
  onnx/backend/test/data/light/README.md
  onnx/backend/test/data/light/light_bvlc_alexnet.onnx
  onnx/backend/test/data/light/light_bvlc_alexnet_output_0.pb
  onnx/backend/test/data/light/light_densenet121.onnx
  onnx/backend/test/data/light/light_densenet121_output_0.pb
  onnx/backend/test/data/light/light_inception_v1.onnx
  onnx/backend/test/data/light/light_inception_v1_output_0.pb
  onnx/backend/test/data/light/light_inception_v2.onnx
  onnx/backend/test/data/light/light_inception_v2_output_0.pb
  onnx/backend/test/data/light/light_resnet50.onnx
  onnx/backend/test/data/light/light_resnet50_output_0.pb
  onnx/backend/test/data/light/light_shufflenet.onnx
  onnx/backend/test/data/light/light_shufflenet_output_0.pb
  onnx/backend/test/data/light/light_squeezenet.onnx
  onnx/backend/test/data/light/light_squeezenet_output_0.pb
  onnx/backend/test/data/light/light_vgg19.onnx
  onnx/backend/test/data/light/light_vgg19_output_0.pb
  onnx/backend/test/data/light/light_zfnet512.onnx
  onnx/backend/test/data/light/light_zfnet512_output_0.pb
  onnx/backend/test/runner/__init__.py
  onnx/test/test_backend_onnxruntime.py
  onnx/test/test_backend_reference.py
  onnx/test/tools_test.py
  onnx/tools/replace_constants.py
Labels: test, run release CIs, reference implementation

#5041 Add clang tidy review in Lint CI
  .github/workflows/clang_tidy_review_post.yml
  .github/workflows/lint.yml
Labels: build pipelines, code style

#4956 Upgrade Protobuf to v21.12 to accept Python Protobuf 4.21
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  .azure-pipelines/Windows-CI.yml
  onnx/examples/Protobufs.ipynb
  onnx/examples/check_model.ipynb
  onnx/examples/load_model.ipynb
  onnx/examples/make_model.ipynb
  requirements-release.txt
  requirements.txt
  setup.py
  workflow_scripts/protobuf/build_protobuf_unix.sh
  workflow_scripts/protobuf/build_protobuf_win.ps1
Labels: build, build pipelines, run release CIs, dependencies

#5087 security Update reuse.yml
  .github/workflows/reuse.yml
Labels: build pipelines

#5020 Allow new `OpSchema`s to be initialized in Python
  docs/docsgen/source/onnx_sphinx.py
  onnx/cpp2py_export.cc
  onnx/defs/gen_doc.py
  onnx/defs/schema.cc
  onnx/defs/schema.h
  onnx/onnx_cpp2py_export/defs.pyi
  onnx/test/schema_test.py
Labels: run release CIs, utility

#5088 Fix shape inference for STFT batch dimension
  onnx/defs/math/defs.cc
Labels: shape inference

#5032 Minor fix from clang-tidy
  onnx/shape_inference/implementation.cc
  onnx/shape_inference/implementation.h
Labels: code style

#5095 Do not set minimum required NumPy version in requirements.txt
  requirements.txt
Labels: build, dependencies

#5061 Clarify spec for Round, Ceil, Floor
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/math/defs.cc
Labels: documentation, spec clarification

#5097 Fix partially failed during doc generation in Linux CI
  .azure-pipelines/Linux-CI.yml
  docs/docsgen/Makefile
Labels: build pipelines, website content

#5101 Make Optional_Clang_Tidy_Review standalone
  .github/workflows/clang_tidy_review.yml
  .github/workflows/clang_tidy_review_post.yml
  .github/workflows/lint.yml
Labels: build pipelines, code style

#5103 Remove `stderr` prints in `version_converter`
  onnx/version_converter/convert.cc
Labels: version converter

#5113 v1.14.0 version update
  docs/Versioning.md
  onnx/common/version.h
  onnx/defs/schema.h
  onnx/helper.py
  onnx/test/helper_test.py
Labels: run release CIs

#5120 Fix some build errors with the latest protobuf version
  onnx/defs/schema.h
Labels: build, run release CIs

#5124 Move requirements from lintrunner.toml
  .lintrunner.toml
  .reuse/dep5
  onnx/reference/ops/op_roi_align.py
  onnx/reference/ops/op_string_normalizer.py
  onnx/test/basic_test.py
  onnx/test/reference_evaluator_backend_test.py
  pyproject.toml
  pyproject_pylint.toml
  requirements-dev.txt
  requirements-lintrunner.txt
Labels: dependencies, code style

#5126 Fix misspellings related to word propagate
  docs/proposals/SymbolicShapeInfProposal.md
  onnx/defs/controlflow/old.cc
  onnx/defs/controlflow/utils.cc
  onnx/defs/data_propagators.h
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
Labels: documentation

#5133 Update .lintrunner.toml to include a merge base
  .lintrunner.toml
  requirements-dev.txt
Labels: code style

#5147 Fix clang-tidy CI: use v0.12.3 to enable comment from forks
  .github/workflows/clang_tidy_review.yml
  .github/workflows/clang_tidy_review_post.yml
Labels: build pipelines, code style

#5065 Use --nbval-current-env instead of --current-env due to deprecation
  setup.cfg
Labels: test

#5156 Extend python API documentation
  docs/docsgen/source/api/hub.rst
Labels: documentation, website content

#5152 Display math in docs
  docs/docsgen/source/conf.py
Labels: website content

#5151 Skip preprocessing model for testing version_converter due to unknown domain
  workflow_scripts/config.py
Labels: test, build pipelines

#5157 Update CIPipelines.md
  docs/CIPipelines.md
Labels: documentation, build pipelines

#5164 Fix permission and bump version as v0.13.0 for clang-tidy-review
  .github/workflows/clang_tidy_review.yml
  .github/workflows/clang_tidy_review_post.yml
Labels: build pipelines, code style

#5090 security: add commit hash to docker file
  .github/dependabot.yml
  .github/workflows/release_linux_x86_64.yml
Labels: run release CIs

#5170 18.04 -> 20.04 Update CIPipelines.md
  docs/CIPipelines.md
Labels: documentation

#5160 Set providers argument in test_backend_onnxruntime.py
  onnx/test/reference_evaluator_backend_test.py
  onnx/test/test_backend_onnxruntime.py
Labels: test

#5158 correct averagepool kernel shape in dilation test case
  docs/Changelog.md
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/averagepool.py
  onnx/backend/test/data/node/test_averagepool_2d_dilations/model.onnx
  onnx/defs/nn/defs.cc
  onnx/test/reference_evaluator_backend_test.py
  onnx/test/shape_inference_test.py
  onnx/test/test_backend_reference.py
Labels: test

#5179 Add security-events permission to the lint action
  .github/workflows/lint.yml
Labels: code style

#5175 Make Azure Pipelines correctly run tests with onnxruntime and enable clang-tidy CI
  .azure-pipelines/Windows-CI.yml
  .clang-tidy
  .github/workflows/clang_tidy_review_post.yml
  onnx/test/test_backend_onnxruntime.py
Labels: test, build pipelines, run release CIs, code style
