Repository onnx/onnx, pull requests merged in 2023-05, with the labels that each got.

#5185 Fix typos in proto files
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
Labels: run release CIs

#5197 Modify OneHot operator explanation
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
Labels: documentation, spec clarification

#5105 Utility to inline model-local functions
  onnx/cpp2py_export.cc
  onnx/inliner.py
  onnx/inliner/inliner.cc
  onnx/inliner/inliner.h
  onnx/onnx_cpp2py_export/inliner.pyi
  onnx/test/cpp/inliner_test.cc
  onnx/test/inliner_test.py
Labels: utility

#5207 Update python.md
  docs/docsgen/source/intro/python.md
Labels: website content

#5210 Pin Python Protobuf version as 3.20.2 for documentation generation CI
  .github/workflows/pages.yml
Labels: build pipelines, website content

#5208 Update the latest IR release date: IR VERSION 9 published on May 5, 2023
  docs/OnnxReleases.md
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
Labels: documentation

#5215 Update classes.md
  docs/docsgen/source/api/classes.md
Labels: documentation, website content

#5169 Extend function type inference to handle missing optional parameters
  onnx/shape_inference/implementation.cc
  onnx/shape_inference/implementation.h
  onnx/test/function_inference_test.py
Labels: shape inference

#5195 Fix ModuleNotFoundError: No module named 'cmake'
  setup.py
Labels: build, run release CIs

#4684 Fix input_1 data to has got same shape as in model
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/castlike.py
  onnx/backend/test/data/node/test_castlike_BFLOAT16_to_FLOAT/model.onnx
  onnx/backend/test/data/node/test_castlike_BFLOAT16_to_FLOAT_expanded/model.onnx
  onnx/backend/test/data/node/test_castlike_FLOAT_to_BFLOAT16/model.onnx
  onnx/backend/test/data/node/test_castlike_FLOAT_to_BFLOAT16_expanded/model.onnx
Labels: test, run release CIs

#5069 Faster reference implementation for operator Conv based on im2col
  onnx/reference/ops/experimental/op_im2col.py
  onnx/reference/ops/op_conv.py
  onnx/reference/ops_optimized/__init__.py
  onnx/reference/ops_optimized/op_conv_optimized.py
  onnx/reference/reference_evaluator.py
  onnx/test/reference_evaluator_backend_test.py
  onnx/test/reference_evaluator_test.py
  pyproject.toml
Labels: reference implementation

#5204 Transpose scalar shape inference
  onnx/defs/tensor/defs.cc
  onnx/test/shape_inference_test.py
Labels: shape inference

#5112 Support textproto as a serialization format
  onnx/__init__.py
  onnx/serialization.py
  onnx/test/basic_test.py
  onnx/test/test_external_data.py
Labels: run release CIs, utility

#5191 Deprecate Python 3.7 due to EOL
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  .azure-pipelines/Windows-CI.yml
  .github/workflows/clang_tidy_review_post.yml
  .github/workflows/manylinux/entrypoint.sh
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  onnx/__init__.py
  onnx/reference/ops/_op_list.py
  onnx/reference/ops/aionnx_preview_training/_op_list.py
  onnx/serialization.py
  onnx/test/basic_test.py
  pyproject.toml
  requirements-dev.txt
  requirements.txt
Labels: build, build pipelines, run release CIs, dependencies

#5223 Fix a couple of shape inference issues
  onnx/defs/generator/old.cc
  onnx/shape_inference/implementation.cc
  onnx/shape_inference/implementation.h
  onnx/test/data_propagation_test.py
  onnx/test/model_inference_test.py
  onnx/test/shape_inference_test.py
Labels: shape inference, partial data propagation

#5224 Use consistent newer NumPy version in all release pipelines
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  onnx/reference/ops_optimized/op_conv_optimized.py
  requirements-release.txt
Labels: build pipelines, run release CIs

#5086 Fix broken link for joining slack
  community/sigs.md
Labels: documentation

#5233 Stop uploading onnx-weekly package to TestPyPI
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  requirements-release.txt
Labels: build pipelines, run release CIs

#5261 Skip not implemented failures for tests with ORT 1.15
  onnx/test/test_backend_onnxruntime.py
Labels: test, run release CIs

#5196 Support protobuf v22.x in cmake
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/MacOS-CI.yml
  .azure-pipelines/Windows-CI.yml
  .github/workflows/weekly_mac_ci.yml
  CMakeLists.txt
  onnx/defs/parser.cc
  onnx/inliner/inliner.cc
Labels: build, run release CIs, dependencies
