Repository onnx/onnx, pull requests merged in 2023-01, with the labels that each got.

#4654 Adopt lintrunner for linting
  .azure-pipelines/Linux-CI.yml
  .azure-pipelines/Windows-CI.yml
  .editorconfig
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/operator.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/codeql.yml
  .github/workflows/lint.yaml
  .github/workflows/pages.yml
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  .github/workflows/weekly_mac_ci.yml
  .gitignore
  .gitmodules
  .lintrunner.toml
  RELEASE-MANAGEMENT.md
  docs/CIPipelines.md
  docs/CONTRIBUTING.md
  onnx/__init__.py
  onnx/backend/test/runner/__init__.py
  onnx/common/file_utils.h
  onnx/defs/math/defs.cc
  onnx/defs/nn/defs.cc
  onnx/defs/optional/defs.cc
  onnx/defs/printer.cc
  onnx/defs/printer.h
  onnx/defs/shape_inference.cc
  onnx/helper.py
  onnx/numpy_helper.py
  onnx/reference/README.md
  onnx/reference/op_run.py
  onnx/reference/ops/op_cast.py
  onnx/reference/ops/op_conv.py
  onnx/reference/ops/op_eyelike.py
  onnx/reference/ops/op_non_max_suppression.py
  onnx/reference/ops/op_reduce_log_sum.py
  onnx/reference/ops/op_resize.py
  onnx/reference/ops/op_sequence_insert.py
  onnx/reference/ops/op_tfidf_vectorizer.py
  onnx/reference/reference_evaluator.py
  onnx/test/cpp/parser_test.cc
  onnx/version_converter/adapters/transformers.h
  pyproject.toml
  requirements-dev.txt
  setup.py
  tools/protoc-gen-mypy.bat
  tools/protoc-gen-mypy.py
  tools/style.sh
  tools/update_doc.bat
Labels: run release CIs, code style

#4748 Add attribute type in documentation
  docs/docsgen/source/conf.py
  docs/docsgen/source/expect_onnxruntime.rst
  docs/docsgen/source/onnx_sphinx.py
Labels: website content

#4753 Remove operators under development from the documentation
  docs/docsgen/source/conf.py
  docs/docsgen/source/onnx_sphinx.py
Labels: website content

#4710 Fix reference implementation for ArgMin, ArgMax, Reduce*
  onnx/reference/op_run.py
  onnx/reference/ops/_op.py
  onnx/reference/ops/op_argmax.py
  onnx/reference/ops/op_argmin.py
  onnx/reference/ops/op_constant.py
  onnx/reference/ops/op_constant_of_shape.py
  onnx/reference/ops/op_if.py
  onnx/reference/ops/op_loop.py
  onnx/reference/ops/op_reduce_l1.py
  onnx/reference/ops/op_reduce_l2.py
  onnx/reference/ops/op_reduce_log_sum.py
  onnx/reference/ops/op_reduce_log_sum_exp.py
  onnx/reference/ops/op_reduce_max.py
  onnx/reference/ops/op_reduce_mean.py
  onnx/reference/ops/op_reduce_min.py
  onnx/reference/ops/op_reduce_prod.py
  onnx/reference/ops/op_reduce_sum.py
  onnx/reference/ops/op_reduce_sum_square.py
  onnx/reference/ops/op_scan.py
  onnx/reference/ops/op_sequence_map.py
  onnx/reference/ops/op_squeeze.py
  onnx/reference/ops/op_where.py
  onnx/reference/reference_evaluator.py
  onnx/test/reference_evaluator_backend_test.py
  onnx/test/reference_evaluator_test.py
Labels: reference implementation

#4714 Add reference implementation for domain ai.onnx.ml
  onnx/reference/ops/aionnxml/__init__.py
  onnx/reference/ops/aionnxml/_common_classifier.py
  onnx/reference/ops/aionnxml/_op_list.py
  onnx/reference/ops/aionnxml/_op_run_aionnxml.py
  onnx/reference/ops/aionnxml/op_array_feature_extractor.py
  onnx/reference/ops/aionnxml/op_binarizer.py
  onnx/reference/ops/aionnxml/op_dict_vectorizer.py
  onnx/reference/ops/aionnxml/op_feature_vectorizer.py
  onnx/reference/ops/aionnxml/op_imputer.py
  onnx/reference/ops/aionnxml/op_label_encoder.py
  onnx/reference/ops/aionnxml/op_linear_classifier.py
  onnx/reference/ops/aionnxml/op_linear_regressor.py
  onnx/reference/ops/aionnxml/op_normalizer.py
  onnx/reference/ops/aionnxml/op_one_hot_encoder.py
  onnx/reference/ops/aionnxml/op_scaler.py
  onnx/reference/ops/aionnxml/op_svm_classifier.py
  onnx/reference/ops/aionnxml/op_svm_helper.py
  onnx/reference/ops/aionnxml/op_svm_regressor.py
  onnx/reference/ops/aionnxml/op_tree_ensemble_classifier.py
  onnx/reference/ops/aionnxml/op_tree_ensemble_helper.py
  onnx/reference/ops/aionnxml/op_tree_ensemble_regressor.py
  onnx/reference/reference_evaluator.py
  onnx/test/reference_evaluator_ml_test.py
Labels: reference implementation

#4765 Make web content creation (pages.yml) automatically trigger
  .github/workflows/codeql.yml
  .github/workflows/pages.yml
  docs/OnnxReleases.md
Labels: website content

#4721 Fix types deprecated in `numpy==1.24`
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/bernoulli.py
  onnx/backend/test/case/node/castlike.py
  onnx/backend/test/runner/__init__.py
  onnx/reference/ops/op_where.py
Labels: run release CIs

#4773 Swap colors on operators diff in the documentation
  docs/docsgen/source/onnx_sphinx.py
Labels: website content

#4741 Download test data
  onnx/hub.py
  onnx/test/hub_test.py
Labels: run release CIs, onnx hub

#4776 Fix missing page for ai.onnx.ml domain
  docs/docsgen/source/onnx_sphinx.py
Labels: website content

#4743 Add missing class Split_18 in reference implementation
  onnx/reference/ops/_op_list.py
  onnx/reference/ops/op_split.py
  onnx/test/reference_evaluator_test.py
Labels: reference implementation

#4763 Enable pylint for onnx
  .github/workflows/lint.yaml
  .lintrunner.toml
  docs/Operators.md
  docs/TestCoverage.md
  onnx/__init__.py
  onnx/backend/base.py
  onnx/backend/sample/ops/__init__.py
  onnx/backend/test/case/model/__init__.py
  onnx/backend/test/case/node/gru.py
  onnx/backend/test/case/node/lstm.py
  onnx/backend/test/case/node/rnn.py
  onnx/backend/test/case/node/transpose.py
  onnx/backend/test/report/coverage.py
  onnx/backend/test/runner/__init__.py
  onnx/backend/test/stat_coverage.py
  onnx/checker.py
  onnx/compose.py
  onnx/defs/__init__.py
  onnx/defs/gen_doc.py
  onnx/external_data_helper.py
  onnx/gen_proto.py
  onnx/helper.py
  onnx/hub.py
  onnx/numpy_helper.py
  onnx/parser.py
  onnx/printer.py
  onnx/reference/reference_evaluator.py
  onnx/shape_inference.py
  onnx/test/automatic_upgrade_test.py
  onnx/test/basic_test.py
  onnx/test/compose_test.py
  onnx/test/helper_test.py
  onnx/test/hub_test.py
  onnx/test/reference_evaluator_backend_test.py
  onnx/test/reference_evaluator_test.py
  onnx/test/shape_inference_test.py
  onnx/test/symbolic_shape_test.py
  onnx/tools/net_drawer.py
  onnx/tools/update_model_dims.py
  onnx/utils.py
  pyproject.toml
  pyproject_pylint.toml
  tools/mypy-onnx.py
Labels: code style

#4801 Fix pages Changes.md
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/nn/defs.cc
Labels: documentation

#4792 Fix attribute substitution within subgraphs during function type/shape inference
  onnx/shape_inference/implementation.cc
  onnx/test/model_inference_test.py
Labels: shape inference

#4795 fix version_conversion error of Pad-2 to Pad-11 caused by missing value attribu…
  onnx/test/version_converter_test.py
  onnx/version_converter/adapters/pad_10_11.h
Labels: version converter

#4806 Fix typo in documentation
  docs/docsgen/source/intro/concepts.rst
Labels: website content

#4807 Fix DFT documentation typo
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/math/defs.cc
Labels: website content

#4720 Expose check_function in Python API
  docs/docsgen/source/api/checker.rst
  onnx/checker.py
  onnx/cpp2py_export.cc
  onnx/onnx_cpp2py_export/checker.pyi
  onnx/test/checker_test.py
Labels: utility

#4817 Fix incorrect member CheckerContext in checker API for web
  docs/docsgen/source/api/checker.rst
Labels: website content

#4808 Remove import-and-import-from check in codeql
  .github/codeql/codeql-config.yml
  .github/workflows/codeql.yml
Labels: code style

#4811 Update governance to deal with steering committee vacancy
  community/readme.md
Labels: documentation

#4810 improve README [add a) roadmap, b) community meeting]
  README.md
Labels: documentation

#4788 cleanup in governance file
  community/readme.md
  community/repo_guidelines.md
Labels: documentation
