Repository onnx/onnx, pull requests merged in 2024-09, with the labels that each got.

#6342 The latest protobuf pkg 5.28.0 is failing on Windows. use the one pre…
  .github/workflows/release_win.yml
Labels: run release CIs

#6345 Set up codecov test analysis
  .github/workflows/main.yml
Labels: do not merge

#6347 [Cherry-Pick] Fix protobuf pkg 5.28.0 failing on Windows (#6342)
  .github/workflows/release_win.yml
Labels: run release CIs

#6327 [Cherry-Pick] Fix main url checks (#6312)
  .github/workflows/check_urls.yml
  docs/ImplementingAnOnnxBackend.md
  docs/docsgen/source/intro/converters.md
Labels: run release CIs

#6346 Extend printer and parser to support invalid identifiers
  docs/Syntax.md
  onnx/defs/parser.cc
  onnx/defs/parser.h
  onnx/defs/printer.cc
  onnx/test/cpp/parser_test.cc
Labels: onnx parser, release notes

#6304 Some performance fixes in C++ code, use of emplace instead of insert
  onnx/common/file_utils.h
  onnx/common/ir.h
  onnx/common/tensor.h
  onnx/defs/data_type_utils.cc
  onnx/defs/data_type_utils.h
  onnx/defs/math/defs.cc
  onnx/defs/schema.cc
  onnx/defs/schema.h
  onnx/defs/sequence/defs.cc
  onnx/defs/tensor/utils.cc
  onnx/defs/tensor/utils.h
  onnx/shape_inference/implementation.cc
  onnx/shape_inference/implementation.h
Labels: review needed: operators approvers

#6358 Fix typo in the GroupNorm description
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/nn/defs.cc
  onnx/defs/nn/old.cc
  onnx/reference/ops/op_quantize_linear.py
  onnx/test/version_converter/automatic_upgrade_test.py
Labels: spec clarification

#6362 Update Protobuf to latest version (Win)
  .github/workflows/release_win.yml
Labels: run release CIs

#6375 Fix wrong publishing target (onnx instead of onnx-weekly)
  .github/workflows/create_release.yml
Labels: run release CIs

#6378 Fix clang-tidy warnings
  .clang-tidy
  onnx/checker.h
  onnx/common/ir.h
  onnx/common/ir_pb_converter.cc
  onnx/common/model_helpers.cc
  onnx/common/status.cc
  onnx/common/status.h
  onnx/defs/data_type_utils.cc
  onnx/defs/data_type_utils.h
  onnx/defs/function.h
  onnx/defs/math/old.cc
  onnx/defs/nn/defs.cc
  onnx/defs/nn/old.cc
  onnx/defs/parser.cc
  onnx/defs/parser.h
  onnx/defs/printer.cc
  onnx/defs/schema.cc
  onnx/defs/schema.h
  onnx/shape_inference/implementation.h
  onnx/version_converter/convert.cc
  onnx/version_converter/helper.cc
Labels: run release CIs

#6382 Revert Python finding logic and some CMake fixes for Windows
  CMakeLists.txt
  setup.py
Labels: run release CIs

#6383 Enable more compiler warnings
  CMakeLists.txt
  onnx/common/path.h
Labels: run release CIs

#6391 Avoid returning const vectors
  onnx/defs/generator/defs.cc
  onnx/defs/math/defs.cc
  onnx/defs/math/old.cc
  onnx/defs/sequence/defs.cc
  onnx/defs/shape_inference.cc
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/defs/tensor/utils.cc
  onnx/defs/tensor_proto_util.cc
  onnx/defs/tensor_proto_util.h
  onnx/defs/tensor_util.cc
  onnx/defs/tensor_util.h
Labels: run release CIs

#6392 Fix more clang-tidy warnings
  .clang-tidy
  CMakeLists.txt
  onnx/defs/data_type_utils.cc
  onnx/defs/nn/defs.cc
  onnx/defs/printer.cc
  onnx/defs/schema.h
  onnx/defs/tensor/defs.cc
  onnx/shape_inference/implementation.cc
  onnx/version_converter/convert.cc
Labels: run release CIs

#6396 Fix more static analyser warnings
  onnx/checker.cc
  onnx/common/ir_pb_converter.cc
  onnx/defs/controlflow/old.cc
  onnx/defs/controlflow/utils.cc
  onnx/defs/math/old.cc
  onnx/defs/shape_inference.h
  onnx/inliner/inliner.cc
Labels: run release CIs

#6398 Add clang-tidy checks and fix warnings
  .clang-tidy
  onnx/checker.cc
  onnx/checker.h
  onnx/common/interned_strings.cc
  onnx/common/interned_strings.h
  onnx/common/ir.h
  onnx/common/status.cc
  onnx/common/tensor.h
  onnx/defs/controlflow/defs.cc
  onnx/defs/data_type_utils.cc
  onnx/defs/function.cc
  onnx/defs/function.h
  onnx/defs/generator/defs.cc
  onnx/defs/math/defs.cc
  onnx/defs/parser.h
  onnx/defs/reduction/old.cc
  onnx/defs/reduction/utils.cc
  onnx/defs/schema.cc
  onnx/defs/sequence/defs.cc
  onnx/defs/shape_inference.h
  onnx/defs/tensor/defs.cc
  onnx/defs/tensor/old.cc
  onnx/shape_inference/attribute_binder.h
  onnx/shape_inference/implementation.h
  onnx/version_converter/adapters/adapter.h
  onnx/version_converter/adapters/axes_input_to_attribute.h
  onnx/version_converter/adapters/axis_input_to_attribute.h
  onnx/version_converter/adapters/extend_supported_types.h
  onnx/version_converter/adapters/group_normalization_20_21.h
  onnx/version_converter/adapters/reshape_4_5.h
  onnx/version_converter/adapters/reshape_5_4.h
  onnx/version_converter/adapters/scan_8_9.h
  onnx/version_converter/adapters/scan_9_8.h
  onnx/version_converter/adapters/split_12_13.h
  onnx/version_converter/adapters/split_13_12.h
  onnx/version_converter/adapters/split_17_18.h
  onnx/version_converter/adapters/upsample_6_7.h
  onnx/version_converter/adapters/upsample_9_8.h
  onnx/version_converter/convert.cc
  onnx/version_converter/convert.h
Labels: run release CIs

#6399 Use -Wall -Wextra on APPLE platforms
  CMakeLists.txt
Labels: run release CIs
