Repository onnx/onnx, pull requests merged in 2024-10, with the labels that each got.

#6407 Support official Python launcher on Windows
  tools/protoc-gen-mypy.bat
Labels: run release CIs

#6421 Update op_pool_common.py, add missing "| None"
  onnx/reference/ops/op_pool_common.py
Labels: reference implementation

#6427 Fix parser to handle empty optional parameters in edge cases
  onnx/defs/parser.cc
  onnx/defs/parser.h
  onnx/test/cpp/parser_test.cc
  onnx/test/parser_test.py
Labels: onnx parser

#6429 Enable more clang-tidy checks
  .clang-tidy
  onnx/checker.cc
  onnx/checker.h
  onnx/common/proto_util.h
  onnx/common/status.h
  onnx/common/tensor.h
  onnx/defs/controlflow/old.cc
  onnx/defs/logical/defs.cc
  onnx/defs/logical/old.cc
  onnx/defs/math/old.cc
  onnx/defs/parser.cc
  onnx/defs/parser.h
  onnx/defs/printer.cc
  onnx/defs/reduction/old.cc
  onnx/defs/rnn/old.cc
  onnx/defs/schema.cc
  onnx/defs/schema.h
  onnx/defs/shape_inference.cc
  onnx/defs/shape_inference.h
  onnx/defs/tensor/utils.cc
  onnx/defs/traditionalml/utils.h
  onnx/inliner/inliner.cc
  onnx/py_utils.h
  onnx/shape_inference/implementation.h
  onnx/test/cpp/data_propagation_test.cc
  onnx/test/cpp/function_context_test.cc
  onnx/test/cpp/function_verify_test.cc
  onnx/test/cpp/shape_inference_test.cc
  onnx/test/cpp/test_main.cc
  onnx/version_converter/adapters/axis_input_to_attribute.h
  onnx/version_converter/adapters/cast_9_8.h
  onnx/version_converter/adapters/clip_10_11.h
  onnx/version_converter/adapters/dropout_11_12.h
  onnx/version_converter/adapters/gemm_6_7.h
  onnx/version_converter/adapters/gemm_7_6.h
  onnx/version_converter/adapters/gridsample_19_20.h
  onnx/version_converter/adapters/maxpool_8_7.h
  onnx/version_converter/adapters/pad_10_11.h
  onnx/version_converter/adapters/q_dq_21_20.h
  onnx/version_converter/adapters/resize_10_11.h
  onnx/version_converter/adapters/scatter_10_11.h
  onnx/version_converter/adapters/slice_9_10.h
  onnx/version_converter/adapters/softmax_12_13.h
  onnx/version_converter/adapters/sum_8_7.h
  onnx/version_converter/adapters/topk_9_10.h
  onnx/version_converter/adapters/upsample_8_9.h
  onnx/version_converter/adapters/upsample_9_10.h
  onnx/version_converter/adapters/upsample_9_8.h
  onnx/version_converter/convert.cc
  onnx/version_converter/convert.h
Labels: better engineering

#6435 Update IR spec to clarify optional input/output availability
  docs/IR.md
Labels: spec clarification

#6377 Create a workflow to suggest lintrunner fixes
  .github/workflows/lint.yml
Labels: do not merge

#6439 Fix ODR violations
  onnx/defs/schema.cc
  onnx/defs/schema.h
Labels: run release CIs

#6450 Use enum class for StatusCategory and StatusCode
  onnx/common/model_helpers.cc
  onnx/common/status.cc
  onnx/common/status.h
  onnx/defs/parser.h
Labels: run release CIs, better engineering

#6449 Fix static analyzer warnings
  onnx/common/array_ref.h
  onnx/common/ir.h
  onnx/common/ir_pb_converter.cc
  onnx/cpp2py_export.cc
  onnx/defs/shape_inference.h
  onnx/test/cpp/function_verify_test.cc
  onnx/test/cpp/shape_inference_test.cc
  onnx/version_converter/adapters/type_restriction.h
Labels: run release CIs, better engineering

#6448 Add missing CHECK_PARSER_STATUS
  onnx/defs/parser.cc
Labels: onnx parser

#6444 Simplify protobuf linking
  CMakeLists.txt
  README.md
  cmake/summary.cmake
Labels: run release CIs

#6373 Migrate to ubuntu-24.04 runner
  .github/workflows/main.yml
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
Labels: run release CIs

#6483 Remove pypi publishing inside "release_"
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
Labels: build, better engineering

#6482 Update ruff to 0.7.0
  onnx/backend/test/runner/__init__.py
  pyproject.toml
  requirements-lintrunner.txt
Labels: better engineering

#6474 Add more type annotations and fix warnings in Python code
  onnx/external_data_helper.py
  onnx/helper.py
  onnx/mapping.py
  onnx/model_container.py
  onnx/shape_inference.py
  onnx/subbyte.py
Labels: better engineering

#6487 Remove __STDC_FORMAT_MACROS
  CMakeLists.txt
Labels: better engineering

#6330 Bump protobuf to 5.28.3
  .github/workflows/main.yml
  .github/workflows/pages.yml
  CMakeLists.txt
  requirements-release.txt
Labels: run release CIs

#6503 Fix GlobalLpPool input types
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/nn/defs.cc
  onnx/defs/nn/old.cc
Labels: operator, release notes
