Repository onnx/onnx, pull requests merged in 2024-11, with the labels that each got.

#6510 Bugfix fix file name in create_release.yml
  .github/workflows/create_release.yml
Labels: run release CIs

#6462 Move to using protogen's .pyi file generator
  .gitignore
  CMakeLists.txt
  onnx/helper.py
  tools/protoc-gen-mypy.py
Labels: run release CIs, better engineering

#6369 Fix reference implementation for ConcatFromSequence
  onnx/reference/ops/op_concat_from_sequence.py
  onnx/test/reference_evaluator_test.py
Labels: do not merge

#6526 Migration to FindPython3.cmake
  .github/workflows/clang_tidy_review.yml
  .github/workflows/manylinux/entrypoint.sh
  .github/workflows/win_no_exception_ci.yml
  CMakeLists.txt
  cmake/ONNXConfigVersion.cmake.in
  cmake/Utils.cmake
  cmake/summary.cmake
  pyproject.toml
  setup.py
  tools/protoc-gen-mypy.sh.in
Labels: run release CIs, release notes

#6542 Remove usage of Mac12-Runner
  .github/workflows/release_mac.yml
  .github/workflows/release_test_weekly_sdist.yml
Labels: run release CIs, do not merge

#6543 Add python 3.13 for release_* workflows
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win.yml
  requirements-min.txt
Labels: run release CIs

#6545 Simplify CMake argument handling in setup.py
  setup.py
Labels: build

#6546 Fix of the devbuild publish-workflow
  .github/workflows/create_release.yml
Labels: run release CIs

#6497 Remove/raise exception when external file exists during onnx.save
  onnx/external_data_helper.py
Labels: release notes
