Repository onnx/onnx, pull requests merged in 2024-07, with the labels that each got.

#6170 Makes to_array, from_array support custom numpy dtype, support float16 type in parser
  .github/workflows/main.yml
  docs/docsgen/source/api/custom_element_types.md
  docs/docsgen/source/api/index.md
  docs/docsgen/source/api/numpy_helper.md
  docs/docsgen/source/technical/int4.md
  onnx/_custom_element_types.py
  onnx/backend/test/case/node/cast.py
  onnx/defs/parser.cc
  onnx/helper.py
  onnx/numpy_helper.py
  onnx/reference/custom_element_types.py
  onnx/reference/op_run.py
  onnx/reference/ops/_helpers.py
  onnx/reference/ops/_op_common_pool.py
  onnx/reference/ops/_op_list.py
  onnx/reference/ops/aionnx_preview_training/op_adagrad.py
  onnx/reference/ops/aionnx_preview_training/op_momentum.py
  onnx/reference/ops/aionnxml/op_svm_classifier.py
  onnx/reference/ops/aionnxml/op_tree_ensemble_regressor.py
  onnx/reference/ops/op_batch_normalization.py
  onnx/reference/ops/op_cast.py
  onnx/reference/ops/op_col2im.py
  onnx/reference/ops/op_constant.py
  onnx/reference/ops/op_conv.py
  onnx/reference/ops/op_dequantize_linear.py
  onnx/reference/ops/op_dft.py
  onnx/reference/ops/op_dropout.py
  onnx/reference/ops/op_gemm.py
  onnx/reference/ops/op_hardmax.py
  onnx/reference/ops/op_loop.py
  onnx/reference/ops/op_max_unpool.py
  onnx/reference/ops/op_negative_log_likelihood_loss.py
  onnx/reference/ops/op_quantize_linear.py
  onnx/reference/ops/op_rnn.py
  onnx/reference/ops/op_roi_align.py
  onnx/reference/ops/op_stft.py
  onnx/reference/ops/op_topk.py
  onnx/test/helper_test.py
  onnx/test/numpy_helper_test.py
  onnx/test/parser_test.py
  onnx/test/reference_evaluator_test.py
  onnx/test/test_backend_reference.py
  onnx/test/version_utils.py
Labels: run release CIs

#6230 move examples dir (https://github.com/onnx/onnx/issues/6087)
  REUSE.toml
  examples/Protobufs.ipynb
  examples/check_model.ipynb
  examples/load_model.ipynb
  examples/make_model.ipynb
  examples/np_array_tensorproto.ipynb
  examples/resources/single_relu.onnx
  examples/resources/single_relu_new.onnx
  examples/resources/tensor.pb
  examples/resources/two_transposes.onnx
  examples/save_model.ipynb
  examples/shape_inference.ipynb
Labels: better engineering

#6250 Handle the optional input in infer_node_outputs
  onnx/shape_inference.py
  onnx/test/inference_function_test.py
Labels: release notes

#6217 Add check on dimensions in Gemm opset 6
  onnx/defs/math/old.cc
Labels: review needed: operators approvers
