Repository onnx/onnx, pull requests merged in 2025-03, with the labels that each got.

#6724 Update preview_source_dist_test.yml
  .github/workflows/create_release.yml
  .github/workflows/preview_source_dist_test.yml
  .github/workflows/release_test_weekly_sdist.yml
Labels: run release CIs

#6725 Harmonize protobuf versions by upgrading to a minimum protobuf version of 25.1 and fix CI error
  .github/workflows/auto_update_doc.yml
  .github/workflows/win_no_exception_ci.yml
  workflow_scripts/protobuf/build_protobuf_unix.sh
  workflow_scripts/protobuf/build_protobuf_win.ps1
Labels: topic: build, run release CIs, auto update doc, protobuf

#6755 Include `backend.py` in source distribution
  MANIFEST.in
Labels: topic: build

#6641 Add multi-device execution support in ONNX
  REUSE.toml
  docs/proposals/ONNXMultiDeviceProposal.md
  docs/proposals/ShardingFormalism.md
  docs/proposals/images/composing_broadcast_axes.png
  onnx/__init__.py
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
Labels: module: spec, release notes

#6762 Simplify checkout submodules
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
Labels: run release CIs

#6760 Clarify minimum Protobuf version in INSTALL.md
  INSTALL.md
Labels: auto update doc

#6765 Improve condition in create_release.yml
  .github/workflows/create_release.yml
Labels: run release CIs

#6766 Remove separate onnx-directory in release_win.yml
  .github/workflows/release_win.yml
Labels: run release CIs

#6774 chore(config): set persist credentials to false
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_mac_freethreading.yml
  .github/workflows/release_sdist.yml
Labels: run release CIs

#6770 Use CMAKE_COMPILER_IS_GNUCXX for g++
  CMakeLists.txt
Labels: run release CIs

#6776 Merge requirements-release_freethreading into requirements-release
  .github/workflows/release_mac_freethreading.yml
  requirements-release.txt
  requirements-release_freethreading.txt
Labels: run release CIs

#6780 Bump ruff to 0.9.10
  requirements-lintrunner.txt
Labels: run release CIs

#6786 Update sdist_test.yml
  .github/workflows/sdist_test.yml
Labels: run release CIs

#6792 Update auto_update_doc.yml
  .github/workflows/auto_update_doc.yml
Labels: auto update doc

#6797 fix wrong use of always in release_linux_x86_64.yml
  .github/workflows/release_linux_x86_64.yml
Labels: module: CI pipelines

#6783 Update gtest to version > v1.16.0 (commit of 8March25)
  cmake/external/googletest.cmake
Labels: run release CIs

#6799 hard code docker image docker://quay.io/pypa/manylinux2014_x86_64:2025.02.28-1 in release pipeline
  .github/workflows/release_linux_x86_64.yml
Labels: run release CIs

#6825 Use ONNX_WERROR=ON in all jobs
  .github/workflows/main.yml
  .github/workflows/pages.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_mac_freethreading.yml
  .github/workflows/release_win.yml
  .github/workflows/release_win_freethreading.yml
  CMakeLists.txt
Labels: topic: build

#6831 Improve source build testing
  .github/workflows/preview_source_dist_test.yml
Labels: run release CIs

#6809 use HEAD_SHA instead of HEAD_REF in auto_update_doc.yml
  .github/workflows/auto_update_doc.yml
Labels: run release CIs

#6832 Fix clang-tidy warnings
  .clang-tidy
  CMakeLists.txt
  onnx/checker.h
  onnx/common/interned_strings.h
  onnx/common/ir.h
  onnx/common/ir_pb_converter.cc
  onnx/common/status.h
  onnx/defs/attr_proto_util.cc
  onnx/defs/attr_proto_util.h
  onnx/defs/function.h
  onnx/defs/parser.h
  onnx/defs/schema.h
  onnx/defs/sequence/defs.cc
  onnx/defs/shape_inference.h
  onnx/defs/tensor/utils.h
  onnx/defs/traditionalml/defs.cc
  onnx/test/cpp/function_verify_test.cc
  onnx/version_converter/adapters/resize_10_11.h
Labels: run release CIs

#6833 Update pypa / manylinux2014_x86_64 in release_linux_x86_64.yml to 2025.03.22-2
  .github/workflows/release_linux_x86_64.yml
Labels: run release CIs

#6830 Fix the ONNX_BUILD_CUSTOM_PROTOBUF bug introduced by PR#6495.
  CMakeLists.txt
Labels: run release CIs

#6804 Bump protobuf to v30.1
  .github/workflows/main.yml
  .github/workflows/main_freethreading.yml
  CMakeLists.txt
  cmake/ProtoBufPatch.cmake
Labels: run release CIs

#6837 replace quansight-labs/setup-python with actions/setup-python
  .github/workflows/auto_update_doc.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/main_freethreading.yml
  .github/workflows/pages.yml
  .github/workflows/pr_checks.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_mac_freethreading.yml
  .github/workflows/release_sdist.yml
  .github/workflows/release_win.yml
  .github/workflows/release_win_freethreading.yml
  .github/workflows/weekly_mac_ci.yml
  .github/workflows/win_no_exception_ci.yml
Labels: run release CIs

#6826 Better support of sanitizers
  .github/workflows/main.yml
  .github/workflows/main_freethreading.yml
  CMakeLists.txt
  cmake/external/FindSanitizer.cmake
Labels: topic: build

#6841 integrate release_mac_freethreading into release_mac
  .github/workflows/create_release.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_mac_freethreading.yml
Labels: run release CIs
