Repository onnx/onnx, pull requests merged in 2025-08, with the labels that each got.

#7151 Update manylinux_2014 -> manylinux_2_28
  .github/workflows/release_linux.yml
Labels: run release CIs, topic: bc breaking

#7198 Create CPPLINT.cfg
  CPPLINT.cfg
Labels: module: CI pipelines

#6987 Remove BUILD_ONNX_PYTHON
  CMakeLists.txt
Labels: topic: bc breaking

#7220 Update required Python version to 3.10 and related fixes
  onnx/__init__.py
  onnx/backend/test/case/node/__init__.py
  onnx/backend/test/runner/__init__.py
  onnx/backend/test/runner/item.py
  onnx/external_data_helper.py
  onnx/helper.py
  onnx/onnx_cpp2py_export/defs.pyi
  onnx/reference/ops/aionnxml/op_tree_ensemble.py
  onnx/reference/ops/op_resize.py
  onnx/serialization.py
  onnx/test/compose_test.py
  onnx/test/test_backend_reference.py
  onnx/tools/net_drawer.py
  pyproject.toml
Labels: topic: bc breaking

#7221 Remove conditional code for Python 3.9 in CI and requirements*txt
  .github/install_test.yml
  .github/workflows/manylinux/entrypoint.sh
  .github/workflows/release_mac.yml
  .github/workflows/win_no_exception_ci.yml
  requirements-min.txt
  requirements-release_test.txt
Labels: run release CIs, test ONNX Model Zoo

#7232 adapt to numpy req min, Update requirements.txt
  requirements.txt
Labels: run release CIs

#7250 Update figures; Update RELEASE-MANAGEMENT.md
  RELEASE-MANAGEMENT.md
Labels: topic: documentation

#7254 Require ml_dtypes>=0.5.0
  requirements.txt
Labels: dependencies
