Repository onnx/onnx, pull requests merged in 2025-05, with the labels that each got.

#6945 Use requirements-release_build in entrypoint.sh
  .github/workflows/manylinux/entrypoint.sh
Labels: run release CIs

#6946 Replace requirements-release.txt with requirements-release_build.txt
  .github/workflows/release_mac.yml
  .github/workflows/release_sdist.yml
Labels: run release CIs

#6888 Clarify the `axes` input of [un]Squeeze to be 1D tensors
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/tensor/defs.cc
Labels: topic: operator

#6947 [feat] Introduce source_date_epoch for reproducible builds (wheels, linux)
  .github/workflows/main.yml
  .github/workflows/manylinux/entrypoint.sh
  .github/workflows/release_linux.yml
  CMakeLists.txt
Labels: run release CIs

#6934 Update CMake to 3.24 and use LINK_LIBRARY:WHOLE_ARCHIVE
  CMakeLists.txt
  cmake/Utils.cmake
Labels: topic: build, run release CIs

#6978 Fix CMake EXPORT
  CMakeLists.txt
Labels: run release CIs

#6968 Simplify CMake code and fix some issues
  CMakeLists.txt
  cmake/ONNXConfig.cmake.in
  cmake/unittest.cmake
  onnx/test/cpp/test_main.cc
Labels: run release CIs

#6986 Update stale workflow to not close issues that should stay open
  .github/workflows/stale.yml
Labels: no-stale

#6988 Use [[maybe_unused]]
  onnx/defs/schema.h
Labels: run release CIs

#6963 Update IRv10 brief docs
  onnx/onnx-ml.proto
  onnx/onnx-ml.proto3
  onnx/onnx.in.proto
  onnx/onnx.proto
  onnx/onnx.proto3
Labels: topic: documentation

#6949 Fix dubious ownership in repository at '/github/workspace'
  .github/workflows/manylinux/entrypoint.sh
  .github/workflows/release_linux.yml
Labels: run release CIs

#6992 Simplify proto source file generation
  CMakeLists.txt
Labels: run release CIs
