Repository onnx/onnx, pull requests merged in 2025-09, with the labels that each got.

#7278 Clean up shape inference imports
  onnx/shape_inference.py
Labels: topic: better engineering

#7293 improve abi3audit checks in release_*.yml
  .github/workflows/release_linux.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_win_aarch64.yml
  .github/workflows/release_win_x86_64.yml
Labels: run release CIs

#7304 Update rotary_embedding reference implementation and tests
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/rotaryembedding.py
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim/model.onnx
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim_expanded/model.onnx
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim_expanded/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim_expanded/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_rotary_embedding_no_position_ids_rotary_dim_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim/model.onnx
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim_expanded/model.onnx
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim_expanded/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim_expanded/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_interleaved_rotary_dim_expanded/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim/model.onnx
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim_expanded/model.onnx
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim_expanded/test_data_set_0/input_1.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim_expanded/test_data_set_0/input_2.pb
  onnx/backend/test/data/node/test_rotary_embedding_with_rotary_dim_expanded/test_data_set_0/output_0.pb
  onnx/reference/ops/op_rotary_embedding.py
Labels: module: reference implementation

#7316 Rename variables in rotary embedding reference for clarity
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/nn/defs.cc
  onnx/reference/ops/op_rotary_embedding.py
Labels: module: reference implementation

#7309 Fix testsuite fails on s390x (big-endian)
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/cast.py
  onnx/backend/test/case/node/castlike.py
  onnx/helper.py
  onnx/model_container.py
  onnx/numpy_helper.py
  onnx/test/checker_test.py
  onnx/test/helper_test.py
  onnx/test/test_external_data.py
  onnx/test/version_converter/automatic_upgrade_test.py
  onnx/test/version_converter_test.py
Labels: run release CIs

#7330 Enable macOS + Python 3.13 test
  .github/workflows/main.yml
Labels: run release CIs

#7332 Support Ninja builds
  setup.py
Labels: topic: build, run release CIs
