Repository onnx/onnx, pull requests merged in 2025-02, with the labels that each got.

#6688 Check if wheels should be published before using a job with a deployment environment
  .github/workflows/create_release.yml
Labels: run release CIs

#6672 Bump absl cpp to 20240722.1
  CMakeLists.txt
Labels: run release CIs

#6692 remove twine from requirements-dev-file
  requirements-dev.txt
Labels: topic: better engineering

#6702 Fix Pad operator example in Python API docs (correct attribute usage)
  docs/PythonAPIOverview.md
Labels: topic: documentation

#6705 Use Python3_add_library to simplify build code
  CMakeLists.txt
  setup.py
Labels: run release CIs

#6709 Remove onnxruntime tests
  onnx/test/elu_test.py
  onnx/test/relu_test.py
  onnx/test/test_backend_onnxruntime.py
  onnx/test/test_with_ort.py
Labels: topic: test

#6706 python313t builds in main_freethreading.yml
  .github/workflows/main_freethreading.yml
  requirements-dev_freethreading.txt
Labels: topic: build

#6704 Improve CMake summary
  cmake/summary.cmake
Labels: topic: build

#6608 Add version converter softmax 13 -> 12
  onnx/test/version_converter_test.py
  onnx/version_converter/adapters/softmax_13_12.h
  onnx/version_converter/convert.h
Labels: run release CIs

#6714 Improve names, add debug variables
  .github/workflows/create_release.yml
  .github/workflows/release_sdist.yml
  setup.py
Labels: run release CIs

#6716 Fix mismatched parenthesis in ci
  .github/workflows/create_release.yml
Labels: module: CI pipelines

#6717 Format rotary embedding documentation
  docs/Changelog.md
  docs/Operators.md
  onnx/defs/nn/defs.cc
Labels: module: spec

#6495 Add protobuf local build option
  CMakeLists.txt
Labels: topic: build, release notes

#6722 Set version 4.25.1 as min protobuf version
  pyproject.toml
  requirements-min.txt
  requirements.txt
Labels: run release CIs

#6723 update auto_update_doc and create sdist_test.yml
  .github/workflows/auto_update_doc.yml
  .github/workflows/sdist_test.yml
Labels: auto update doc
