Repository onnx/onnx, pull requests merged in 2025-01, with the labels that each got.

#6618 Enable more readability checks
  .clang-tidy
  onnx/checker.cc
  onnx/common/assertions.h
  onnx/common/ir.h
  onnx/cpp2py_export.cc
  onnx/defs/controlflow/old.cc
  onnx/defs/controlflow/utils.cc
  onnx/defs/math/defs.cc
  onnx/defs/math/old.cc
  onnx/defs/nn/old.cc
  onnx/defs/printer.cc
  onnx/defs/shape_inference.cc
  onnx/defs/traditionalml/defs.cc
  onnx/test/cpp/shape_inference_test.cc
  onnx/version_converter/adapters/scan_9_8.h
Labels: run release CIs, better engineering

#6560 Move INSTALL instruction to separate file
  INSTALL.md
  README.md
Labels: documentation

#6619 Improve attribute checking in `CategoryMapper`
  onnx/defs/traditionalml/defs.cc
  onnx/test/shape_inference_test.py
Labels: run release CIs

#6632 Enable isort rules in ruff formatter
  onnx/helper.py
  onnx/onnx_cpp2py_export/defs.pyi
  pyproject.toml
  requirements-lintrunner.txt
Labels: better engineering

#6631 Remove struct and leverage ml_dtypes in helper tests
  onnx/test/helper_test.py
  onnx/test/numpy_helper_test.py
  requirements-dev.txt
  requirements-release.txt
Labels: test, better engineering

#6636 Fix the bfloat16 test in helper for min numpy version
  onnx/test/helper_test.py
Labels: run release CIs

#6638 Fix numpy_helper to_array
  onnx/numpy_helper.py
  onnx/test/helper_test.py
Labels: run release CIs, module: utility

#6643 Add cmake dependency only when system cmake is not available (backend version)
  backend.py
  pyproject.toml
  setup.py
Labels: topic: build, run release CIs

#6639 Deprecate all type casting functions
  docs/docsgen/source/api/helper.md
  docs/docsgen/source/api/numpy_helper.md
  onnx/helper.py
  onnx/numpy_helper.py
  onnx/subbyte.py
  requirements.txt
Labels: run release CIs, module: utility, release notes, topic: deprecation

#6652 Relax naming requirements in IR spec
  docs/IR.md
Labels: topic: spec

#6650 Fix pooling pads issues
  docs/Operators.md
  docs/TestCoverage.md
  onnx/backend/test/case/node/averagepool.py
  onnx/backend/test/case/node/lppool.py
  onnx/backend/test/case/node/maxpool.py
  onnx/backend/test/data/node/test_averagepool_2d_ceil_last_window_starts_on_pad/model.onnx
  onnx/backend/test/data/node/test_averagepool_2d_ceil_last_window_starts_on_pad/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_averagepool_2d_ceil_last_window_starts_on_pad/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_averagepool_3d_dilations_large_count_include_pad_is_1_ceil_mode_is_True/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_image_decoder_decode_jpeg2k_rgb/test_data_set_0/input_0.pb
  onnx/backend/test/data/node/test_lppool_1d_default/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_lppool_2d_default/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_lppool_2d_pads/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_lppool_2d_same_lower/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_lppool_2d_same_upper/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_lppool_2d_strides/test_data_set_0/output_0.pb
  onnx/backend/test/data/node/test_lppool_3d_default/test_data_set_0/output_0.pb
  onnx/reference/ops/op_pool_common.py
  onnx/test/test_backend_onnxruntime.py
Labels: module: reference implementation

#6661 Remove unnecessary secrets in pipeline
  .github/workflows/create_release.yml
  .github/workflows/release_linux_x86_64.yml
Labels: run release CIs

#6662 Hardening of checkout
  .github/workflows/auto_update_doc.yml
  .github/workflows/check_urls.yml
  .github/workflows/codeql.yml
  .github/workflows/lint.yml
  .github/workflows/pages.yml
  .github/workflows/pr_checks.yml
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
  .github/workflows/release_mac.yml
  .github/workflows/release_sdist.yml
  .github/workflows/release_win.yml
  .github/workflows/reuse.yml
  .github/workflows/weekly_mac_ci.yml
  .github/workflows/win_no_exception_ci.yml
Labels: run release CIs

#6667 Use DeprecationWarning
  onnx/helper.py
  onnx/numpy_helper.py
  onnx/subbyte.py
Labels: topic: better engineering

#6671 Improve release_linux_*.yml
  .github/workflows/release_linux_aarch64.yml
  .github/workflows/release_linux_x86_64.yml
Labels: run release CIs
